/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark3rdoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Dark3rdoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[-1.822, 0.434, -2.636]}>
        <mesh geometry={nodes.Cube030.geometry} material={newMaterials.Outlets_Baked} />
        <mesh geometry={nodes.Cube030_1.geometry} material={newMaterials.Charger_Baked} />
      </group>
      <group position={[-1.478, 1.142, -2.493]}>
        <mesh geometry={nodes.Cube039.geometry} material={newMaterials['CertificatesPY_Baked.001']} />
        <mesh geometry={nodes.Cube039_1.geometry} material={newMaterials['CertificateFE_Baked.001']} />
        <mesh geometry={nodes.Cube039_2.geometry} material={newMaterials['CertificatesBE_Baked.001']} />
      </group>
      <group position={[1.763, 2.301, -2.45]} scale={1.103}>
        <mesh geometry={nodes.Cube065.geometry} material={newMaterials.Dyinglight_Baked} />
        <mesh geometry={nodes.Cube065_1.geometry} material={newMaterials.FinalFantasy_Baked} />
        <mesh geometry={nodes.Cube065_2.geometry} material={newMaterials.Horizon_Baked} />
        <mesh geometry={nodes.Cube065_3.geometry} material={newMaterials.GodFall_Baked} />
        <mesh geometry={nodes.Cube065_4.geometry} material={newMaterials.Farcry_Baked} />
        <mesh geometry={nodes.Cube065_5.geometry} material={newMaterials.Re7_Baked} />
        <mesh geometry={nodes.Cube065_6.geometry} material={newMaterials.Metro_Baked} />
        <mesh geometry={nodes.Cube065_7.geometry} material={newMaterials.Creed_Baked} />
        <mesh geometry={nodes.Cube065_8.geometry} material={newMaterials.Dirt5_Baked} />
        <mesh geometry={nodes.Cube065_9.geometry} material={newMaterials.EldenRing_Baked} />
      </group>
      <mesh geometry={nodes.Ps5_Control_Baked.geometry} material={newMaterials['Ps5 Control_Baked']} position={[1.686, 1.604, -2.422]} />
      <mesh geometry={nodes.Jewellery_Box_Baked.geometry} material={newMaterials['Jewellery Box_Baked']} position={[1.167, 2.201, -2.477]} />
      <group position={[1.69, 0.85, -2.454]}>
        <mesh geometry={nodes.Cube067.geometry} material={newMaterials['Wall Cabinet_Baked']} />
        <mesh geometry={nodes.Cube067_1.geometry} material={newMaterials['Majestic Trophy_Baked']} />
        <mesh geometry={nodes.Cube067_2.geometry} material={newMaterials['Basket Trophy_Baked']} />
        <mesh geometry={nodes.Cube067_3.geometry} material={newMaterials['Chess Trophy.001_Baked']} />
        <mesh geometry={nodes.Cube067_4.geometry} material={newMaterials.Frog_Baked} />
        <mesh geometry={nodes.Cube067_5.geometry} material={newMaterials['Single Column Trophy_Baked']} />
        <mesh geometry={nodes.Cube067_6.geometry} material={newMaterials.horse_statue_01_Baked} />
        <mesh geometry={nodes.Cube067_7.geometry} material={newMaterials.Speaker_Baked} />
        <mesh geometry={nodes.Cube067_8.geometry} material={newMaterials.PS5_Baked} />
        <mesh geometry={nodes.Cube067_9.geometry} material={newMaterials['Vr Headset_Baked']} />
        <mesh geometry={nodes.Cube067_10.geometry} material={newMaterials.Camera_Baked} />
        <mesh geometry={nodes.Cube067_11.geometry} material={newMaterials.VinylSleeves_Baked} />
        <mesh geometry={nodes.Cube067_12.geometry} material={newMaterials.AMDisk_Baked} />
        <mesh geometry={nodes.Cube067_13.geometry} material={newMaterials.AMAlbum_Baked} />
        <mesh geometry={nodes.Cube067_14.geometry} material={newMaterials['Vinyl Player_Baked']} />
        <mesh geometry={nodes.Cube067_15.geometry} material={newMaterials['DVD-MCU-1_Iron Man_Baked']} />
        <mesh geometry={nodes.Cube067_16.geometry} material={newMaterials['DVD-MCU-2_The Incredible Hulk_Baked']} />
        <mesh geometry={nodes.Cube067_17.geometry} material={newMaterials['DVD-MCU-3_Iron Man 2_Baked']} />
        <mesh geometry={nodes.Cube067_18.geometry} material={newMaterials['DVD-MCU-4_Thor_Baked']} />
        <mesh geometry={nodes.Cube067_19.geometry} material={newMaterials['DVD-MCU-5_Captain America The First Avenger_Baked']} />
        <mesh geometry={nodes.Cube067_20.geometry} material={newMaterials['DVD-MCU-6_Marvels The Avengers_Baked.001']} />
        <mesh geometry={nodes.Cube067_21.geometry} material={newMaterials.Typewriter_Baked} />
        <mesh geometry={nodes.Cube067_22.geometry} material={newMaterials['Scale_Baked.001']} />
        <mesh geometry={nodes.Cube067_23.geometry} material={newMaterials['ShelvePots_Baked.001']} />
        <mesh geometry={nodes.Cube067_24.geometry} material={newMaterials['Boot.R_Baked.001']} />
        <mesh geometry={nodes.Cube067_25.geometry} material={newMaterials['Boot.L_Baked.001']} />
      </group>
      <mesh geometry={nodes.Painting_Baked.geometry} material={newMaterials.Painting_Baked} position={[0.123, 1.87, -2.646]} />
    </group>
  )
}

useGLTF.preload('/Dark3rdoffice.glb')
