/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark2ndoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Dark2ndoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Phone15_Baked.geometry} material={newMaterials.Phone15_Baked} position={[0.95, 0.832, 0.706]} />
      <mesh geometry={nodes.Cup_of_coffee_Baked.geometry} material={newMaterials['Cup of coffee_Baked']} position={[0.793, 0.835, 0.778]} />
      <mesh geometry={nodes.DialPhone_Baked.geometry} material={newMaterials.DialPhone_Baked} position={[0.791, 0.828, 0.488]} />
      <mesh geometry={nodes.Clock_Baked.geometry} material={newMaterials.Clock_Baked} position={[0.562, 0.853, 0.769]} />
      <group position={[0.196, 0.827, 1.449]} rotation={[-Math.PI, 1.309, -Math.PI]} scale={0.777}>
        <mesh geometry={nodes.flowers_In_vaze004.geometry} material={newMaterials.PlantPot_Baked} />
        <mesh geometry={nodes.flowers_In_vaze004_1.geometry} material={newMaterials.Leaves2_Baked} />
        <mesh geometry={nodes.flowers_In_vaze004_2.geometry} material={newMaterials.Leaves1_Baked} />
      </group>
      <group position={[0.908, 0.207, 0.937]} rotation={[Math.PI, 0, 0]} scale={[-1.745, -1, -1.222]}>
        <mesh geometry={nodes.Plane001.geometry} material={newMaterials['tapis 30.001']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={newMaterials['CornerTableBlack_Baked.001']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={newMaterials.Safe_Baked} />
        <mesh geometry={nodes.Plane001_3.geometry} material={newMaterials.Cabinet_Baked} />
        <mesh geometry={nodes.Plane001_4.geometry} material={newMaterials.ComputerCase_Baked} />
        <mesh geometry={nodes.Plane001_5.geometry} material={newMaterials.Bottle_Baked} />
        <mesh geometry={nodes.Plane001_6.geometry} material={newMaterials['Table Lamp_Baked']} />
        <mesh geometry={nodes.Plane001_7.geometry} material={newMaterials['Playing Cards Box_Baked.001']} />
        <mesh geometry={nodes.Plane001_8.geometry} material={newMaterials.Book_Baked} />
        <mesh geometry={nodes.Plane001_9.geometry} material={newMaterials.Eyeglasses_Baked} />
        <mesh geometry={nodes.Plane001_10.geometry} material={newMaterials.DeskFan_Baked} />
        <mesh geometry={nodes.Plane001_11.geometry} material={newMaterials.PictureFrame_Baked} />
        <mesh geometry={nodes.Plane001_12.geometry} material={newMaterials['vase_Baked.001']} />
        <mesh geometry={nodes.Plane001_13.geometry} material={newMaterials['Gaming Mousepad_Baked']} />
        <mesh geometry={nodes.Plane001_14.geometry} material={newMaterials.KeyBoard_Baked} />
        <mesh geometry={nodes.Plane001_15.geometry} material={newMaterials.GamingMouse_Baked} />
        <mesh geometry={nodes.Plane001_16.geometry} material={newMaterials.The_Hunter_And_His_Dog_vs_c_Baked} />
        <mesh geometry={nodes.Plane001_17.geometry} material={newMaterials.Laptop_Baked} />
        <mesh geometry={nodes.Plane001_18.geometry} material={newMaterials['KeyboardLap_Baked.001']} />
        <mesh geometry={nodes.Plane001_19.geometry} material={newMaterials.Monitor_Baked} />
        <mesh geometry={nodes.Plane001_20.geometry} material={newMaterials.OfficeChair_Baked} />
      </group>
      <mesh geometry={nodes.Laptop_Screen.geometry} material={newMaterials.Laptop_Baked} position={[0.356, 0.848, 1.144]} />
      <mesh geometry={nodes.Monitor_Screen.geometry} material={newMaterials.Monitor_Baked} position={[1.352, 0.828, 0.289]} />
    </group>
  )
}

useGLTF.preload('/Dark2ndoffice.glb')
