/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark2ndoffice.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Dark2ndoffice.glb')
  const newMaterials = convertMaterialsToBasic(materials)

  // Fan reference
  const fanRef = useRef()

  // Rotate around Z-axis first. (Try Y or X if needed.)
  const localAxis = new THREE.Vector3(1, 0, 1)

  useFrame((state, delta) => {
    if (fanRef.current) {
      localAxis.normalize()
      // Rotate using the mesh's LOCAL axis (correct circular rotation)
      fanRef.current.rotateOnAxis(localAxis, -delta * 8)
    }
  })

  return (
    <group {...props} dispose={null}>
      <group position={[0.95, 0.859, 0.706]}>
        <mesh geometry={nodes.Плоскость002.geometry} material={newMaterials.Phone15_Baked} />
        <mesh geometry={nodes.Плоскость002_1.geometry} material={newMaterials['Cup of coffee_Baked']} />
      </group>

      <mesh geometry={nodes.Clock_Baked.geometry} material={newMaterials.Clock_Baked} position={[0.562, 0.88, 0.769]} />

      <group position={[0.196, 0.855, 1.449]}>
        <mesh geometry={nodes.flowers_In_vaze002.geometry} material={newMaterials.PlantPot_Baked} />
        <mesh geometry={nodes.flowers_In_vaze002_1.geometry} material={newMaterials.Leaves1_Baked} />
      </group>

      <group position={[0.903, 0.226, 0.939]}>
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN.geometry} material={newMaterials['henrikCarpet_Baked.003']} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_1.geometry} material={newMaterials.Safe_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_2.geometry} material={newMaterials['vase_Baked.001']} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_3.geometry} material={newMaterials['Table Lamp_Baked']} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_4.geometry} material={newMaterials.Eyeglasses_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_5.geometry} material={newMaterials['Playing Cards Box_Baked.001']} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_6.geometry} material={newMaterials.The_Hunter_And_His_Dog_vs_c_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_7.geometry} material={newMaterials.Laptop_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_8.geometry} material={newMaterials.Monitor_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_9.geometry} material={newMaterials.Bottle_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_10.geometry} material={newMaterials['CornerTableBlack_Baked.001']} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_11.geometry} material={newMaterials.GamingMouse_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_12.geometry} material={newMaterials['Gaming Mousepad_Baked']} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_13.geometry} material={newMaterials.KeyBoard_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_14.geometry} material={newMaterials.ComputerCase_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_15.geometry} material={newMaterials.Cabinet_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_16.geometry} material={newMaterials.GamingChairSupp_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_17.geometry} material={newMaterials['KeyboardLap_Baked.001']} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_18.geometry} material={newMaterials.DialPhone_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_19.geometry} material={newMaterials.DeskFan_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_20.geometry} material={newMaterials.PictureFrame_Baked} />
        <mesh geometry={nodes.Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HEN_21.geometry} material={newMaterials.Book_Baked} />
      </group>

      {/* Fan group - rotating correctly */}
      <group ref={fanRef} position={[0.47, 1.003, 0.576]}>
        <mesh geometry={nodes.Fan_Baked.geometry} material={newMaterials.DeskFan_Baked} />
      </group>

      <mesh geometry={nodes.LaptopScreen.geometry} material={newMaterials['Laptop.001_Baked']} position={[0.356, 0.877, 1.144]} />
    </group>
  )
}

useGLTF.preload('/models/Dark2ndoffice.glb')
