/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark4thoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Dark4thoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);
  
  return (
    <group {...props} dispose={null}>
      <group position={[-2.006, 0.552, -0.554]}>
        <mesh geometry={nodes['Obj3d66-395056-1-561002'].geometry} material={newMaterials['3rdSetMergedBake_Baked.001']} />
        <mesh geometry={nodes['Obj3d66-395056-1-561002_1'].geometry} material={newMaterials['2ndSetMergedBake_Baked.001']} />
        <mesh geometry={nodes['Obj3d66-395056-1-561002_2'].geometry} material={newMaterials['1stSetMergedBake_Baked']} />
      </group>
      <mesh geometry={nodes.Tree_Pics_Modern_Wall_Decoration_Baked.geometry} material={newMaterials['Tree Pics Modern Wall Decoration_Baked']} position={[-2.316, 1.922, -0.775]} />
      <mesh geometry={nodes.ESPSnakebyte_Baked.geometry} material={newMaterials['ESPSnakebyte_Baked.001']} position={[-1.872, 0.57, -1.533]} />
      <mesh geometry={nodes.BlackCouch_Baked.geometry} material={newMaterials['BlackCouch_Baked.001']} position={[-1.765, 0.209, 0.851]} />
      <group position={[-1.765, 0.209, 0.851]}>
        <mesh geometry={nodes.Plane023.geometry} material={newMaterials['Pillow2_Baked.001']} />
        <mesh geometry={nodes.Plane023_1.geometry} material={newMaterials['Pillow1_Baked.001']} />
      </group>
      <group position={[-1.765, 0.209, 0.851]}>
        <mesh geometry={nodes.Plane024.geometry} material={newMaterials['Pillow3_Baked.001']} />
        <mesh geometry={nodes.Plane024_1.geometry} material={newMaterials.Pillow4_Baked} />
      </group>
      <group position={[-1.969, 0.438, -2.056]} rotation={[0, -1.291, 0]} scale={1.249}>
        <mesh geometry={nodes.Plane007.geometry} material={newMaterials.CaletheaPot_Baked} />
        <mesh geometry={nodes.Plane007_1.geometry} material={newMaterials['CalatheaLeaves_Baked.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Dark4thoffice.glb')
