/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 darkmodeoffice_packed.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { getGLTFLoader } from '../../setuploaders.js'
import { convertMaterialsToBasic } from '../utils/convertToBasic'

export default function Model(props) {
  // ✅ use the global GLTF loader configured with KTX2 + Draco
  const customLoader = getGLTFLoader()

  const { nodes, materials } = useGLTF(
    '/models/darkmodeoffice_packed.glb',
    true,
    undefined,
    (loader) => {
      // If the loader supports these methods, attach them
      if (loader.setDRACOLoader && loader.setKTX2Loader) {
        loader.setDRACOLoader(customLoader.dracoLoader)
        loader.setKTX2Loader(customLoader.ktx2Loader)
      }
    }
  )
        
  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[-15, 1, -15]} scale={0.002}>
        <mesh geometry={nodes.mesh_0.geometry} material={newMaterials['3rdSetMergedBake_Baked.001']} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={newMaterials['2ndSetMergedBake_Baked.001']} />
        <mesh geometry={nodes.mesh_0_2.geometry} material={newMaterials['1stSetMergedBake_Baked']} />
        <mesh geometry={nodes.mesh_0_3.geometry} material={newMaterials['Tree Pics Modern Wall Decoration_Baked']} />
        <mesh geometry={nodes.mesh_0_4.geometry} material={newMaterials['Floor2_Baked.001']} />
        <mesh geometry={nodes.mesh_0_5.geometry} material={newMaterials['BeanBags.001_Baked']} />
        <mesh geometry={nodes.mesh_0_6.geometry} material={newMaterials['ESPSnakebyte_Baked.001']} />
        <mesh geometry={nodes.mesh_0_7.geometry} material={newMaterials.Phone15_Baked} />
        <mesh geometry={nodes.mesh_0_8.geometry} material={newMaterials['Cup of coffee_Baked']} />
        <mesh geometry={nodes.mesh_0_9.geometry} material={newMaterials.DialPhone_Baked} />
        <mesh geometry={nodes.mesh_0_10.geometry} material={newMaterials.Clock_Baked} />
        <mesh geometry={nodes.mesh_0_11.geometry} material={newMaterials.PlantPot_Baked} />
        <mesh geometry={nodes.mesh_0_12.geometry} material={newMaterials.Leaves2_Baked} />
        <mesh geometry={nodes.mesh_0_13.geometry} material={newMaterials.Leaves1_Baked} />
        <mesh geometry={nodes.mesh_0_14.geometry} material={newMaterials['BlackCouch_Baked.001']} />
        <mesh geometry={nodes.mesh_0_15.geometry} material={newMaterials['Pillow2_Baked.001']} />
        <mesh geometry={nodes.mesh_0_16.geometry} material={newMaterials['Pillow1_Baked.001']} />
        <mesh geometry={nodes.mesh_0_17.geometry} material={newMaterials['Pillow3_Baked.001']} />
        <mesh geometry={nodes.mesh_0_18.geometry} material={newMaterials.Pillow4_Baked} />
        <mesh geometry={nodes.mesh_0_19.geometry} material={newMaterials.Shepherd_Baked} />
        <mesh geometry={nodes.mesh_0_20.geometry} material={newMaterials['Bunny Soft Toy.001_Baked']} />
        <mesh geometry={nodes.mesh_0_21.geometry} material={newMaterials.DogBed_Baked} />
        <mesh geometry={nodes.mesh_0_22.geometry} material={newMaterials['Dog bed with toys_Baked']} />
        <mesh geometry={nodes.mesh_0_23.geometry} material={newMaterials.Outlets_Baked} />
        <mesh geometry={nodes.mesh_0_24.geometry} material={newMaterials.Charger_Baked} />
        <mesh geometry={nodes.mesh_0_25.geometry} material={newMaterials['CertificatesPY_Baked.001']} />
        <mesh geometry={nodes.mesh_0_26.geometry} material={newMaterials['CertificateFE_Baked.001']} />
        <mesh geometry={nodes.mesh_0_27.geometry} material={newMaterials['CertificatesBE_Baked.001']} />
        <mesh geometry={nodes.mesh_0_28.geometry} material={newMaterials['tapis 30.001']} />
        <mesh geometry={nodes.mesh_0_29.geometry} material={newMaterials['CornerTableBlack_Baked.001']} />
        <mesh geometry={nodes.mesh_0_30.geometry} material={newMaterials.Safe_Baked} />
        <mesh geometry={nodes.mesh_0_31.geometry} material={newMaterials.Cabinet_Baked} />
        <mesh geometry={nodes.mesh_0_32.geometry} material={newMaterials.ComputerCase_Baked} />
        <mesh geometry={nodes.mesh_0_33.geometry} material={newMaterials.Bottle_Baked} />
        <mesh geometry={nodes.mesh_0_34.geometry} material={newMaterials['Table Lamp_Baked']} />
        <mesh geometry={nodes.mesh_0_35.geometry} material={newMaterials['Playing Cards Box_Baked.001']} />
        <mesh geometry={nodes.mesh_0_36.geometry} material={newMaterials.Book_Baked} />
        <mesh geometry={nodes.mesh_0_37.geometry} material={newMaterials.Eyeglasses_Baked} />
        <mesh geometry={nodes.mesh_0_38.geometry} material={newMaterials.DeskFan_Baked} />
        <mesh geometry={nodes.mesh_0_39.geometry} material={newMaterials.PictureFrame_Baked} />
        <mesh geometry={nodes.mesh_0_40.geometry} material={newMaterials['vase_Baked.001']} />
        <mesh geometry={nodes.mesh_0_41.geometry} material={newMaterials['Gaming Mousepad_Baked']} />
        <mesh geometry={nodes.mesh_0_42.geometry} material={newMaterials.KeyBoard_Baked} />
        <mesh geometry={nodes.mesh_0_43.geometry} material={newMaterials.GamingMouse_Baked} />
        <mesh geometry={nodes.mesh_0_44.geometry} material={newMaterials.The_Hunter_And_His_Dog_vs_c_Baked} />
        <mesh geometry={nodes.mesh_0_45.geometry} material={newMaterials.Laptop_Baked} />
        <mesh geometry={nodes.mesh_0_46.geometry} material={newMaterials['KeyboardLap_Baked.001']} />
        <mesh geometry={nodes.mesh_0_47.geometry} material={newMaterials.Monitor_Baked} />
        <mesh geometry={nodes.mesh_0_48.geometry} material={newMaterials.OfficeChair_Baked} />
        <mesh geometry={nodes.mesh_0_49.geometry} material={newMaterials.Dyinglight_Baked} />
        <mesh geometry={nodes.mesh_0_50.geometry} material={newMaterials.FinalFantasy_Baked} />
        <mesh geometry={nodes.mesh_0_51.geometry} material={newMaterials.Horizon_Baked} />
        <mesh geometry={nodes.mesh_0_52.geometry} material={newMaterials.GodFall_Baked} />
        <mesh geometry={nodes.mesh_0_53.geometry} material={newMaterials.Farcry_Baked} />
        <mesh geometry={nodes.mesh_0_54.geometry} material={newMaterials.Re7_Baked} />
        <mesh geometry={nodes.mesh_0_55.geometry} material={newMaterials.Metro_Baked} />
        <mesh geometry={nodes.mesh_0_56.geometry} material={newMaterials.Creed_Baked} />
        <mesh geometry={nodes.mesh_0_57.geometry} material={newMaterials.Dirt5_Baked} />
        <mesh geometry={nodes.mesh_0_58.geometry} material={newMaterials.EldenRing_Baked} />
        <mesh geometry={nodes.mesh_0_59.geometry} material={newMaterials['Ps5 Control_Baked']} />
        <mesh geometry={nodes.mesh_0_60.geometry} material={newMaterials['Jewellery Box_Baked']} />
        <mesh geometry={nodes.mesh_0_61.geometry} material={newMaterials['Wall Cabinet_Baked']} />
        <mesh geometry={nodes.mesh_0_62.geometry} material={newMaterials['Majestic Trophy_Baked']} />
        <mesh geometry={nodes.mesh_0_63.geometry} material={newMaterials['Basket Trophy_Baked']} />
        <mesh geometry={nodes.mesh_0_64.geometry} material={newMaterials['Chess Trophy.001_Baked']} />
        <mesh geometry={nodes.mesh_0_65.geometry} material={newMaterials.Frog_Baked} />
        <mesh geometry={nodes.mesh_0_66.geometry} material={newMaterials['Single Column Trophy_Baked']} />
        <mesh geometry={nodes.mesh_0_67.geometry} material={newMaterials.horse_statue_01_Baked} />
        <mesh geometry={nodes.mesh_0_68.geometry} material={newMaterials.Speaker_Baked} />
        <mesh geometry={nodes.mesh_0_69.geometry} material={newMaterials.PS5_Baked} />
        <mesh geometry={nodes.mesh_0_70.geometry} material={newMaterials['Vr Headset_Baked']} />
        <mesh geometry={nodes.mesh_0_71.geometry} material={newMaterials.Camera_Baked} />
        <mesh geometry={nodes.mesh_0_72.geometry} material={newMaterials.VinylSleeves_Baked} />
        <mesh geometry={nodes.mesh_0_73.geometry} material={newMaterials.AMDisk_Baked} />
        <mesh geometry={nodes.mesh_0_74.geometry} material={newMaterials.AMAlbum_Baked} />
        <mesh geometry={nodes.mesh_0_75.geometry} material={newMaterials['Vinyl Player_Baked']} />
        <mesh geometry={nodes.mesh_0_76.geometry} material={newMaterials['DVD-MCU-1_Iron Man_Baked']} />
        <mesh geometry={nodes.mesh_0_77.geometry} material={newMaterials['DVD-MCU-2_The Incredible Hulk_Baked']} />
        <mesh geometry={nodes.mesh_0_78.geometry} material={newMaterials['DVD-MCU-3_Iron Man 2_Baked']} />
        <mesh geometry={nodes.mesh_0_79.geometry} material={newMaterials['DVD-MCU-4_Thor_Baked']} />
        <mesh geometry={nodes.mesh_0_80.geometry} material={newMaterials['DVD-MCU-5_Captain America The First Avenger_Baked']} />
        <mesh geometry={nodes.mesh_0_81.geometry} material={newMaterials['DVD-MCU-6_Marvels The Avengers_Baked.001']} />
        <mesh geometry={nodes.mesh_0_82.geometry} material={newMaterials.Typewriter_Baked} />
        <mesh geometry={nodes.mesh_0_83.geometry} material={newMaterials['Scale_Baked.001']} />
        <mesh geometry={nodes.mesh_0_84.geometry} material={newMaterials['ShelvePots_Baked.001']} />
        <mesh geometry={nodes.mesh_0_85.geometry} material={newMaterials['Boot.R_Baked.001']} />
        <mesh geometry={nodes.mesh_0_86.geometry} material={newMaterials['Boot.L_Baked.001']} />
        <mesh geometry={nodes.mesh_0_87.geometry} material={newMaterials.Painting_Baked} />
        <mesh geometry={nodes.mesh_0_88.geometry} material={newMaterials['Wall2_Baked.003']} />
        <mesh geometry={nodes.mesh_0_89.geometry} material={newMaterials.CaletheaPot_Baked} />
        <mesh geometry={nodes.mesh_0_90.geometry} material={newMaterials['CalatheaLeaves_Baked.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/darkmodeoffice_packed.glb')
