/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark1stoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Dark1stoffice.glb')
            
  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor2_Baked.geometry} material={newMaterials['Floor2_Baked.001']} position={[0, -0.01, 0]} />
      <mesh geometry={nodes.BeanBags2.geometry} material={newMaterials['BeanBags.001_Baked']} position={[0.089, 0.481, -0.984]} />
      <mesh geometry={nodes.Shepherd_Baked.geometry} material={newMaterials.Shepherd_Baked} position={[1.89, 0.633, -1.54]} />
      <mesh geometry={nodes.Bunny_Soft_Toy001_Baked.geometry} material={newMaterials['Bunny Soft Toy.001_Baked']} position={[1.449, 0.312, -1.357]} />
      <group position={[1.795, 0.308, -1.476]}>
        <mesh geometry={nodes.Cylinder_Material001_0001.geometry} material={newMaterials.DogBed_Baked} />
        <mesh geometry={nodes.Cylinder_Material001_0001_1.geometry} material={newMaterials['Dog bed with toys_Baked']} />
      </group>
      <mesh geometry={nodes.Wall2_Baked.geometry} material={newMaterials['Wall2_Baked.003']} position={[0.001, 0.008, 0]} />
    </group>
  )
}

useGLTF.preload('/Dark1stoffice.glb')
