/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 darkhomeoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/darkhomeoffice.glb')

  console.log(nodes);
      
  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[-2.006, 0.552, -0.554]}>
        <mesh geometry={nodes['Obj3d66-395056-1-561002'].geometry} material={newMaterials['3rdSetMergedBake_Baked.001']} />
        <mesh geometry={nodes['Obj3d66-395056-1-561002_1'].geometry} material={newMaterials['2ndSetMergedBake_Baked.001']} />
        <mesh geometry={nodes['Obj3d66-395056-1-561002_2'].geometry} material={newMaterials['1stSetMergedBake_Baked']} />
      </group>
      <mesh geometry={nodes.Tree_Pics_Modern_Wall_Decoration_Baked.geometry} material={newMaterials['Tree Pics Modern Wall Decoration_Baked']} position={[-2.316, 1.922, -0.775]} />
      <mesh geometry={nodes.Floor2_Baked.geometry} material={newMaterials['Floor2_Baked.001']} position={[0, -0.01, 0]} />
      <mesh geometry={nodes.BeanBags2.geometry} material={newMaterials['BeanBags.001_Baked']} position={[0.089, 0.481, -0.984]} />
      <mesh geometry={nodes.ESPSnakebyte_Baked.geometry} material={newMaterials['ESPSnakebyte_Baked.001']} position={[-1.872, 0.57, -1.533]} />
      <mesh geometry={nodes.Phone15_Baked.geometry} material={newMaterials.Phone15_Baked} position={[0.95, 0.832, 0.706]} />
      <mesh geometry={nodes.Cup_of_coffee_Baked.geometry} material={newMaterials['Cup of coffee_Baked']} position={[0.793, 0.835, 0.778]} />
      <mesh geometry={nodes.DialPhone_Baked.geometry} material={newMaterials.DialPhone_Baked} position={[0.791, 0.828, 0.488]} />
      <mesh geometry={nodes.Clock_Baked.geometry} material={newMaterials.Clock_Baked} position={[0.562, 0.853, 0.769]} />
      <group position={[0.196, 0.827, 1.449]} rotation={[-Math.PI, 1.309, -Math.PI]} scale={0.777}>
        <mesh geometry={nodes.flowers_In_vaze004.geometry} material={newMaterials.PlantPot_Baked} />
        <mesh geometry={nodes.flowers_In_vaze004_1.geometry} material={newMaterials.Leaves2_Baked} />
        <mesh geometry={nodes.flowers_In_vaze004_2.geometry} material={newMaterials.Leaves1_Baked} />
      </group>
      <mesh geometry={nodes.BlackCouch_Baked.geometry} material={newMaterials['BlackCouch_Baked.001']} position={[-1.765, 0.209, 0.851]} />
      <group position={[-1.765, 0.209, 0.851]}>
        <mesh geometry={nodes.Plane023.geometry} material={newMaterials['Pillow2_Baked.001']} />
        <mesh geometry={nodes.Plane023_1.geometry} material={newMaterials['Pillow1_Baked.001']} />
      </group>
      <group position={[-1.765, 0.209, 0.851]}>
        <mesh geometry={nodes.Plane024.geometry} material={newMaterials['Pillow3_Baked.001']} />
        <mesh geometry={nodes.Plane024_1.geometry} material={newMaterials.Pillow4_Baked} />
      </group>
      <mesh geometry={nodes.Shepherd_Baked.geometry} material={newMaterials.Shepherd_Baked} position={[1.89, 0.633, -1.54]} />
      <mesh geometry={nodes.Bunny_Soft_Toy001_Baked.geometry} material={newMaterials['Bunny Soft Toy.001_Baked']} position={[1.449, 0.312, -1.357]} />
      <group position={[1.795, 0.308, -1.476]}>
        <mesh geometry={nodes.Cylinder_Material001_0001.geometry} material={newMaterials.DogBed_Baked} />
        <mesh geometry={nodes.Cylinder_Material001_0001_1.geometry} material={newMaterials['Dog bed with toys_Baked']} />
      </group>
      <group position={[-1.822, 0.434, -2.636]}>
        <mesh geometry={nodes.Cube030.geometry} material={newMaterials.Outlets_Baked} />
        <mesh geometry={nodes.Cube030_1.geometry} material={newMaterials.Charger_Baked} />
      </group>
      <group position={[-1.478, 1.142, -2.493]}>
        <mesh geometry={nodes.Cube039.geometry} material={newMaterials['CertificatesPY_Baked.001']} />
        <mesh geometry={nodes.Cube039_1.geometry} material={newMaterials['CertificateFE_Baked.001']} />
        <mesh geometry={nodes.Cube039_2.geometry} material={newMaterials['CertificatesBE_Baked.001']} />
      </group>
      <group position={[0.908, 0.207, 0.937]} rotation={[Math.PI, 0, 0]} scale={[-1.745, -1, -1.222]}>
        <mesh geometry={nodes.Plane001.geometry} material={newMaterials['tapis 30.001']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={newMaterials['CornerTableBlack_Baked.001']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={newMaterials.Safe_Baked} />
        <mesh geometry={nodes.Plane001_3.geometry} material={newMaterials.Cabinet_Baked} />
        <mesh geometry={nodes.Plane001_4.geometry} material={newMaterials.ComputerCase_Baked} />
        <mesh geometry={nodes.Plane001_5.geometry} material={newMaterials.Bottle_Baked} />
        <mesh geometry={nodes.Plane001_6.geometry} material={newMaterials['Table Lamp_Baked']} />
        <mesh geometry={nodes.Plane001_7.geometry} material={newMaterials['Playing Cards Box_Baked.001']} />
        <mesh geometry={nodes.Plane001_8.geometry} material={newMaterials.Book_Baked} />
        <mesh geometry={nodes.Plane001_9.geometry} material={newMaterials.Eyeglasses_Baked} />
        <mesh geometry={nodes.Plane001_10.geometry} material={newMaterials.DeskFan_Baked} />
        <mesh geometry={nodes.Plane001_11.geometry} material={newMaterials.PictureFrame_Baked} />
        <mesh geometry={nodes.Plane001_12.geometry} material={newMaterials['vase_Baked.001']} />
        <mesh geometry={nodes.Plane001_13.geometry} material={newMaterials['Gaming Mousepad_Baked']} />
        <mesh geometry={nodes.Plane001_14.geometry} material={newMaterials.KeyBoard_Baked} />
        <mesh geometry={nodes.Plane001_15.geometry} material={newMaterials.GamingMouse_Baked} />
        <mesh geometry={nodes.Plane001_16.geometry} material={newMaterials.The_Hunter_And_His_Dog_vs_c_Baked} />
        <mesh geometry={nodes.Plane001_17.geometry} material={newMaterials.Laptop_Baked} />
        <mesh geometry={nodes.Plane001_18.geometry} material={newMaterials['KeyboardLap_Baked.001']} />
        <mesh geometry={nodes.Plane001_19.geometry} material={newMaterials.Monitor_Baked} />
        <mesh geometry={nodes.Plane001_20.geometry} material={newMaterials.OfficeChair_Baked} />
      </group>
      <group position={[1.763, 2.301, -2.45]} scale={1.103}>
        <mesh geometry={nodes.Cube065.geometry} material={newMaterials.Dyinglight_Baked} />
        <mesh geometry={nodes.Cube065_1.geometry} material={newMaterials.FinalFantasy_Baked} />
        <mesh geometry={nodes.Cube065_2.geometry} material={newMaterials.Horizon_Baked} />
        <mesh geometry={nodes.Cube065_3.geometry} material={newMaterials.GodFall_Baked} />
        <mesh geometry={nodes.Cube065_4.geometry} material={newMaterials.Farcry_Baked} />
        <mesh geometry={nodes.Cube065_5.geometry} material={newMaterials.Re7_Baked} />
        <mesh geometry={nodes.Cube065_6.geometry} material={newMaterials.Metro_Baked} />
        <mesh geometry={nodes.Cube065_7.geometry} material={newMaterials.Creed_Baked} />
        <mesh geometry={nodes.Cube065_8.geometry} material={newMaterials.Dirt5_Baked} />
        <mesh geometry={nodes.Cube065_9.geometry} material={newMaterials.EldenRing_Baked} />
      </group>
      <mesh geometry={nodes.Ps5_Control_Baked.geometry} material={newMaterials['Ps5 Control_Baked']} position={[1.686, 1.604, -2.422]} />
      <mesh geometry={nodes.Jewellery_Box_Baked.geometry} material={newMaterials['Jewellery Box_Baked']} position={[1.167, 2.201, -2.477]} />
      <group position={[1.69, 0.85, -2.454]}>
        <mesh geometry={nodes.Cube067.geometry} material={newMaterials['Wall Cabinet_Baked']} />
        <mesh geometry={nodes.Cube067_1.geometry} material={newMaterials['Majestic Trophy_Baked']} />
        <mesh geometry={nodes.Cube067_2.geometry} material={newMaterials['Basket Trophy_Baked']} />
        <mesh geometry={nodes.Cube067_3.geometry} material={newMaterials['Chess Trophy.001_Baked']} />
        <mesh geometry={nodes.Cube067_4.geometry} material={newMaterials.Frog_Baked} />
        <mesh geometry={nodes.Cube067_5.geometry} material={newMaterials['Single Column Trophy_Baked']} />
        <mesh geometry={nodes.Cube067_6.geometry} material={newMaterials.horse_statue_01_Baked} />
        <mesh geometry={nodes.Cube067_7.geometry} material={newMaterials.Speaker_Baked} />
        <mesh geometry={nodes.Cube067_8.geometry} material={newMaterials.PS5_Baked} />
        <mesh geometry={nodes.Cube067_9.geometry} material={newMaterials['Vr Headset_Baked']} />
        <mesh geometry={nodes.Cube067_10.geometry} material={newMaterials.Camera_Baked} />
        <mesh geometry={nodes.Cube067_11.geometry} material={newMaterials.VinylSleeves_Baked} />
        <mesh geometry={nodes.Cube067_12.geometry} material={newMaterials.AMDisk_Baked} />
        <mesh geometry={nodes.Cube067_13.geometry} material={newMaterials.AMAlbum_Baked} />
        <mesh geometry={nodes.Cube067_14.geometry} material={newMaterials['Vinyl Player_Baked']} />
        <mesh geometry={nodes.Cube067_15.geometry} material={newMaterials['DVD-MCU-1_Iron Man_Baked']} />
        <mesh geometry={nodes.Cube067_16.geometry} material={newMaterials['DVD-MCU-2_The Incredible Hulk_Baked']} />
        <mesh geometry={nodes.Cube067_17.geometry} material={newMaterials['DVD-MCU-3_Iron Man 2_Baked']} />
        <mesh geometry={nodes.Cube067_18.geometry} material={newMaterials['DVD-MCU-4_Thor_Baked']} />
        <mesh geometry={nodes.Cube067_19.geometry} material={newMaterials['DVD-MCU-5_Captain America The First Avenger_Baked']} />
        <mesh geometry={nodes.Cube067_20.geometry} material={newMaterials['DVD-MCU-6_Marvels The Avengers_Baked.001']} />
        <mesh geometry={nodes.Cube067_21.geometry} material={newMaterials.Typewriter_Baked} />
        <mesh geometry={nodes.Cube067_22.geometry} material={newMaterials['Scale_Baked.001']} />
        <mesh geometry={nodes.Cube067_23.geometry} material={newMaterials['ShelvePots_Baked.001']} />
        <mesh geometry={nodes.Cube067_24.geometry} material={newMaterials['Boot.R_Baked.001']} />
        <mesh geometry={nodes.Cube067_25.geometry} material={newMaterials['Boot.L_Baked.001']} />
      </group>
      <mesh geometry={nodes.Painting_Baked.geometry} material={newMaterials.Painting_Baked} position={[0.123, 1.87, -2.646]} />
      <mesh geometry={nodes.Wall2_Baked.geometry} material={newMaterials['Wall2_Baked.003']} position={[0.001, 0.008, 0]} />
      <group position={[-1.969, 0.438, -2.056]} rotation={[0, -1.291, 0]} scale={1.249}>
        <mesh geometry={nodes.Plane007.geometry} material={newMaterials.CaletheaPot_Baked} />
        <mesh geometry={nodes.Plane007_1.geometry} material={newMaterials['CalatheaLeaves_Baked.001']} />
      </group>
      <mesh geometry={nodes.Laptop_Screen.geometry} material={newMaterials.Laptop_Baked} position={[0.356, 0.848, 1.144]} />
      <mesh geometry={nodes.Monitor_Screen.geometry} material={newMaterials.Monitor_Baked} position={[1.352, 0.828, 0.289]} />
    </group>
  )
}

useGLTF.preload('/darkhomeoffice.glb')
