/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 homeofficev5.glb 
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/homeofficev5.glb')

  console.log(nodes);
  
  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1stTextureSet'].geometry} material={newMaterials['1stSetMergedBake_Baked']} position={[-2.293, 2.213, 1.441]} />
      <mesh geometry={nodes['2ndTextureSet'].geometry} material={newMaterials['2ndSetMergedBake_Baked.001']} position={[-1.781, 0.525, -0.644]} />
      <mesh geometry={nodes['3rdTextureSet'].geometry} material={newMaterials['3rdSetMergedBake_Baked.001']} position={[-2.006, 0.552, -0.554]} rotation={[0, -1.268, 0]} />
      <mesh geometry={nodes['4thTextureSet'].geometry} material={newMaterials['4thSetMergedBake_Baked.004']} position={[1.848, 1.041, -2.472]} rotation={[1.566, -0.592, 1.563]} />
      <mesh geometry={nodes.Cup_of_coffee_Baked.geometry} material={newMaterials['Cup of coffee_Baked.002']} position={[0.606, 0.833, 1.682]} rotation={[1.567, 0, -0.003]} />
      <mesh geometry={nodes['6thTextureSet'].geometry} material={newMaterials['6thSetMergedBake_Baked.004']} position={[1.735, 0.829, 0.623]} rotation={[0, -0.004, -0.009]} />
      <mesh geometry={nodes['7thTextureSet'].geometry} material={newMaterials['7thSetMergedBake_Baked.001']} position={[-1.05, 2.199, -2.486]} />
      <mesh geometry={nodes.Basket_Trophy_Baked.geometry} material={newMaterials['Basket Trophy_Baked']} position={[-1.768, 1.798, -2.452]} rotation={[-0.938, -0.242, 3.121]} />
      <group position={[-1.424, 1.812, -2.484]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Sphere_Material002_0003.geometry} material={newMaterials['8thSetMergedBake_Baked.004']} />
        <mesh geometry={nodes.Sphere_Material002_0003_1.geometry} material={newMaterials['8thSetMergedBake_Baked.005']} />
      </group>
      <group position={[-1.478, 0.219, -2.386]} rotation={[0.002, 0.702, 0.002]}>
        <mesh geometry={nodes.Plane019.geometry} material={newMaterials['9thSetMergedBake_Baked.005']} />
        <mesh geometry={nodes.Plane019_1.geometry} material={newMaterials['9thSetMergedBake_Baked.004']} />
        <mesh geometry={nodes.Plane019_2.geometry} material={newMaterials['9thSetMergedBake_Baked.006']} />
      </group>
      <mesh geometry={nodes.Painting_Baked.geometry} material={newMaterials.Painting_Baked} position={[0.123, 1.87, -2.646]} rotation={[1.567, 0, -0.003]} />
      <mesh geometry={nodes['12thTextureSet'].geometry} material={newMaterials['12thSetMergedBake_Baked']} position={[1.149, 2.333, -2.503]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.Ps4_games_Baked.geometry} material={newMaterials['Ps4 games_Baked']} position={[1.894, 2.264, -2.46]} rotation={[0.01, -1.567, -3.128]} />
      <group position={[-1.791, 1.093, -2.488]}>
        <mesh geometry={nodes.Cube009.geometry} material={newMaterials.black} />
        <mesh geometry={nodes.Cube009_1.geometry} material={newMaterials.Material} />
        <mesh geometry={nodes.Cube009_2.geometry} material={newMaterials.Picture_Sc} />
        <mesh geometry={nodes.Cube009_3.geometry} material={newMaterials.Picture_Tc} />
      </group>
      <group position={[0.413, 0.826, 1.656]} rotation={[3.138, -0.003, 3.142]}>
        <mesh geometry={nodes.Cube012.geometry} material={newMaterials.CardBox} />
        <mesh geometry={nodes.Cube012_1.geometry} material={newMaterials.Default} />
        <mesh geometry={nodes.Cube012_2.geometry} material={newMaterials.Galvanized_Steel} />
        <mesh geometry={nodes.Cube012_3.geometry} material={newMaterials['Material.041']} />
        <mesh geometry={nodes.Cube012_4.geometry} material={newMaterials['Material.042']} />
      </group>
      <mesh geometry={nodes.Jewellery_Box.geometry} material={newMaterials['Jewellery Box4K']} position={[1.517, 2.199, -2.455]} rotation={[0.031, 0.01, 0.003]} />
      <group position={[-0.184, 0.497, -2.485]}>
        <mesh geometry={nodes.uv2_uv2_01183.geometry} material={newMaterials['Typewriter_Baked.001']} />
        <mesh geometry={nodes.uv2_uv2_01183_1.geometry} material={newMaterials.Material_37} />
        <mesh geometry={nodes.uv2_uv2_01183_2.geometry} material={newMaterials.Material_85} />
        <mesh geometry={nodes.uv2_uv2_01183_3.geometry} material={newMaterials.Material_49} />
        <mesh geometry={nodes.uv2_uv2_01183_4.geometry} material={newMaterials.Material_73} />
        <mesh geometry={nodes.uv2_uv2_01183_5.geometry} material={newMaterials.Material_25} />
        <mesh geometry={nodes.uv2_uv2_01183_6.geometry} material={newMaterials.Scale_Baked} />
      </group>
      <mesh geometry={nodes.Tree_Pics_Modern_Wall_Decoration_Baked.geometry} material={newMaterials['Tree Pics Modern Wall Decoration_Baked']} position={[-2.316, 1.922, -0.775]} />
      <mesh geometry={nodes.Office_Chair_Baked.geometry} material={newMaterials['5thSetMergedBake_Baked']} position={[1.227, 0.459, 1.21]} rotation={[-0.004, 0.162, 0]} />
      <group position={[1.352, 0.826, 0.289]} rotation={[-0.004, -0.01, 0]}>
        <mesh geometry={nodes.Monitor001.geometry} material={newMaterials['Monitor_Baked.001']} />
        <mesh geometry={nodes.Monitor001_1.geometry} material={newMaterials['Laptop.001_Baked']} />
      </group>
      <mesh geometry={nodes.Keyboard001_Baked.geometry} material={newMaterials['Keyboard.001_Baked']} position={[0.609, 0.827, 1.232]} rotation={[-0.006, 1.551, 0.002]} />
      <mesh geometry={nodes.Floor2_Baked.geometry} material={newMaterials['Floor2_Baked.001']} position={[0, -0.01, 0]} />
      <group position={[0.609, 0.827, 1.232]} rotation={[-0.006, 1.551, 0.002]}>
        <mesh geometry={nodes.CornerTable_1.geometry} material={newMaterials['Material.004']} />
        <mesh geometry={nodes.CornerTable_2.geometry} material={newMaterials['Material.003']} />
      </group>
      <mesh geometry={nodes.Carpet_Baked002.geometry} material={newMaterials.Carpet_Baked} position={[0.907, 0.203, 0.94]} rotation={[-0.004, 0.003, 0]} />
      <mesh geometry={nodes.BeanBags2.geometry} material={newMaterials['BeanBags.001_Baked']} position={[-0.323, 0.515, -0.83]} rotation={[-3.126, -1.339, -3.126]} />
      <mesh geometry={nodes.ESPSnakebyte_Baked.geometry} material={newMaterials['ESPSnakebyte_Baked.001']} position={[-1.872, 0.57, -1.533]} rotation={[0.031, 0.003, -1.489]} scale={[0.008, 0.004, 0.008]} />
      <mesh geometry={nodes.Ps5_Control_Baked.geometry} material={newMaterials['Ps5 Control_Baked.001']} position={[1.686, 1.604, -2.422]} />
      <mesh geometry={nodes.PS5_Baked.geometry} material={newMaterials['PS5_Baked.002']} position={[1.995, 1.585, -2.504]} />
      <group position={[0.104, 0.991, -2.49]} rotation={[0, -1.291, 0]}>
        <mesh geometry={nodes.Plane007.geometry} material={newMaterials.ShelvePots_Baked} />
        <mesh geometry={nodes.Plane007_1.geometry} material={newMaterials.CalatheaLeaves_Baked} />
        <mesh geometry={nodes.Plane007_2.geometry} material={newMaterials['CaletheaPot_Baked.005']} />
      </group>
      <mesh geometry={nodes.Wall2_Baked.geometry} material={newMaterials['Wall2_Baked.001']} position={[0.001, 0.008, 0]} />
      <mesh geometry={nodes.Leather_Sofa002_Baked.geometry} material={newMaterials['Leather Sofa.002_Baked']} position={[-1.718, 0.208, 0.834]} rotation={[0, 1.563, 0]} scale={0.78} />
      <mesh geometry={nodes.Leather_cushion_baked.geometry} material={newMaterials.pillowleather_baked} position={[-1.775, 0.657, 0.3]} rotation={[-0.455, 1.152, 0.433]} scale={0.491} />
      <mesh geometry={nodes.Graypillow_Baked.geometry} material={newMaterials['Graypillow_Baked.001']} position={[-1.763, 0.643, 1.426]} />
    </group>
  )
}

useGLTF.preload('/homeofficev5.glb')
