/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light6thoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Light6thoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[-1.193, 0.615, -28.07]}>
        <mesh geometry={nodes.Object_0034.geometry} material={newMaterials.Canvas_Baked} />
        <mesh geometry={nodes.Object_0034_1.geometry} material={newMaterials['Canvas painting_Baked']} />
        <mesh geometry={nodes.Object_0034_2.geometry} material={newMaterials.Saoirse_Baked} />
        <mesh geometry={nodes.Object_0034_3.geometry} material={newMaterials['Easel.001_Baked']} />
        <mesh geometry={nodes.Object_0034_4.geometry} material={newMaterials.Paintbrushes_Baked} />
        <mesh geometry={nodes.Object_0034_5.geometry} material={newMaterials.Palette_Baked} />
        <mesh geometry={nodes.Object_0034_6.geometry} material={newMaterials.Stool_Baked} />
      </group>
      <mesh geometry={nodes.CornerPlant2_Baked.geometry} material={newMaterials.CornerPlant2_Baked} position={[-1.995, 0.445, -27.591]} />
      <mesh geometry={nodes.CornerPlant2pot_Baked.geometry} material={newMaterials.CornerPlant2pot_Baked} position={[-1.988, 0.248, -27.618]} />
      <mesh geometry={nodes.Round_embossed_flower_carpet_Baked.geometry} material={newMaterials['Round embossed flower carpet_Baked']} position={[-0.818, 0.136, -28.172]} />
      <mesh geometry={nodes.PillowBasket_Baked.geometry} material={newMaterials.PillowBasket_Baked} position={[-0.047, 0.265, -30.907]} />
      <mesh geometry={nodes.Rattan_Knot_Chair2_Baked001.geometry} material={newMaterials['Rattan Knot Chair.001_Baked']} position={[-0.439, 0.377, -29.794]} />
      <mesh geometry={nodes.cowrug_Baked.geometry} material={newMaterials['peau de vache_Baked.001']} position={[-0.892, 0.142, -29.806]} />
      <group position={[-0.961, 0.333, -29.846]} rotation={[Math.PI, 0, Math.PI]} scale={0.612}>
        <mesh geometry={nodes.Sankofa_Stool010.geometry} material={newMaterials['weaving_Baked.001']} />
        <mesh geometry={nodes.Sankofa_Stool010_1.geometry} material={newMaterials['rattan_Baked.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Light6thoffice.glb')
