/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light4thoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Light4thoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[-1.46, 2.502, -32.373]}>
        <mesh geometry={nodes.Maillage008.geometry} material={newMaterials.basilPot_Baked} />
        <mesh geometry={nodes.Maillage008_1.geometry} material={newMaterials.basil_Baked} />
      </group>
      <group position={[-1.818, 2.235, -30.952]}>
        <mesh geometry={nodes.grass_lambert9_0002.geometry} material={newMaterials.ShelvePlant1Pot_Baked} />
        <mesh geometry={nodes.grass_lambert9_0002_1.geometry} material={newMaterials.ShelvePlant1_Baked} />
      </group>
      <mesh geometry={nodes.ShelvePlant3_Baked.geometry} material={newMaterials.ShelvePlant3_Baked} position={[-1.142, 2.004, -32.407]} />
      <group position={[-1.797, 1.252, -30.716]}>
        <mesh geometry={nodes.Plane029.geometry} material={newMaterials.BookshelfPlantPot_Baked} />
        <mesh geometry={nodes.Plane029_1.geometry} material={newMaterials.BookshelfPlant_Baked} />
      </group>
      <mesh geometry={nodes.CornerShelf_baked.geometry} material={newMaterials.cornershelfbaked} position={[-2.267, 1.556, -32.394]} />
      <group position={[-2.233, 1.557, -32.352]}>
        <mesh geometry={nodes.Object_0027.geometry} material={newMaterials.mariobake} />
        <mesh geometry={nodes.Object_0027_1.geometry} material={newMaterials.falloutbake} />
        <mesh geometry={nodes.Object_0027_2.geometry} material={newMaterials.sansbake} />
        <mesh geometry={nodes.Object_0027_3.geometry} material={newMaterials.chicabake} />
        <mesh geometry={nodes.Object_0027_4.geometry} material={newMaterials.bonniebake} />
        <mesh geometry={nodes.Object_0027_5.geometry} material={newMaterials.foxybake} />
        <mesh geometry={nodes.Object_0027_6.geometry} material={newMaterials.fredbake} />
        <mesh geometry={nodes.Object_0027_7.geometry} material={newMaterials.ironmanbake} />
        <mesh geometry={nodes.Object_0027_8.geometry} material={newMaterials.capbake} />
        <mesh geometry={nodes.Object_0027_9.geometry} material={newMaterials.spiderbake} />
        <mesh geometry={nodes.Object_0027_10.geometry} material={newMaterials.DrStrange_baked_Baked} />
      </group>
      <group position={[-2.23, 2.222, -32.363]}>
        <mesh geometry={nodes.Plano003.geometry} material={newMaterials['Asplenium Nidu Plant.001_Baked']} />
        <mesh geometry={nodes.Plano003_1.geometry} material={newMaterials.aspleniumpotbaked} />
      </group>
      <group position={[-2.31, 1.24, -30.62]}>
        <mesh geometry={nodes.Maillage009.geometry} material={newMaterials['Stack of books.002_Baked']} />
        <mesh geometry={nodes.Maillage009_1.geometry} material={newMaterials['Stack of books_Baked']} />
      </group>
      <mesh geometry={nodes.WoodenBox_Baked.geometry} material={newMaterials.WoodenBox_Baked} position={[-2.593, 2.024, -28.707]} />
      <group position={[-2.285, 1.265, -30.314]}>
        <mesh geometry={nodes.Object_1003.geometry} material={newMaterials.BornToDie_Baked} />
        <mesh geometry={nodes.Object_1003_1.geometry} material={newMaterials.VinylStack2_Baked} />
        <mesh geometry={nodes.Object_1003_2.geometry} material={newMaterials.VinylStack_Baked} />
        <mesh geometry={nodes.Object_1003_3.geometry} material={newMaterials.VinylStack3_Baked} />
        <mesh geometry={nodes.Object_1003_4.geometry} material={newMaterials['Hand made clay vase.001_Baked']} />
        <mesh geometry={nodes.Object_1003_5.geometry} material={newMaterials['ShelvesRight.001_Baked']} />
        <mesh geometry={nodes.Object_1003_6.geometry} material={newMaterials.StrawVase_Baked} />
        <mesh geometry={nodes.Object_1003_7.geometry} material={newMaterials.ToyPlane_Baked} />
        <mesh geometry={nodes.Object_1003_8.geometry} material={newMaterials.ShelfBasket_Baked} />
        <mesh geometry={nodes.Object_1003_9.geometry} material={newMaterials['White vase.001_Baked']} />
        <mesh geometry={nodes.Object_1003_10.geometry} material={newMaterials.Shelves_Baked} />
        <mesh geometry={nodes.Object_1003_11.geometry} material={newMaterials.UpBooks_Baked} />
        <mesh geometry={nodes.Object_1003_12.geometry} material={newMaterials.Magz_Sub_Baked} />
        <mesh geometry={nodes.Object_1003_13.geometry} material={newMaterials.BookStack1_Baked} />
        <mesh geometry={nodes.Object_1003_14.geometry} material={newMaterials.Bookstack7_Baked} />
        <mesh geometry={nodes.Object_1003_15.geometry} material={newMaterials.BookStack2_Baked} />
        <mesh geometry={nodes.Object_1003_16.geometry} material={newMaterials.BookStack4_Baked} />
        <mesh geometry={nodes.Object_1003_17.geometry} material={newMaterials.Photography_Baked} />
        <mesh geometry={nodes.Object_1003_18.geometry} material={newMaterials.Bookstack6_Baked} />
        <mesh geometry={nodes.Object_1003_19.geometry} material={newMaterials.BookStack3_Baked} />
        <mesh geometry={nodes.Object_1003_20.geometry} material={newMaterials.Bookstack5_Baked} />
      </group>
    </group>
  )
}

useGLTF.preload('/Light4thoffice.glb')
