/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light1stoffice.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Light1stoffice.glb')
  const newMaterials = convertMaterialsToBasic(materials);

  // Fan reference
    const fanRef = useRef()
  
    // Rotate around Z-axis first. (Try Y or X if needed.)
    const localAxis = new THREE.Vector3(1, 0, 1)
  
    useFrame((state, delta) => {
      if (fanRef.current) {
        localAxis.normalize()
        // Rotate using the mesh's LOCAL axis (correct circular rotation)
        fanRef.current.rotateOnAxis(localAxis, delta * 70)
      }
    })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Backdrop_Baked.geometry} material={newMaterials['Backdrop_Baked.003']} position={[0, -0.01, -29.998]} />
      <group position={[1.486, 0.147, -28.476]}>
        <mesh geometry={nodes.pCube209_slipa_0001.geometry} material={newMaterials.Slippers_Baked} />
        <mesh geometry={nodes.pCube209_slipa_0001_1.geometry} material={newMaterials['Desk Top_Baked']} />
        <mesh geometry={nodes.pCube209_slipa_0001_2.geometry} material={newMaterials.RattanCompchair_Baked} />
        <mesh geometry={nodes.pCube209_slipa_0001_3.geometry} material={newMaterials.UnderBasket_Baked} />
      </group>
      <mesh geometry={nodes.RattanTrashcan_Baked.geometry} material={newMaterials.RattanTrashcan_Baked} position={[1.605, 0.131, -27.725]} />
      <mesh geometry={nodes.BinderStacks_Baked.geometry} material={newMaterials.BinderStacks_Baked} position={[2.296, 0.605, -29.329]} />
      <mesh geometry={nodes.Laptop_Baked.geometry} material={newMaterials.Laptop_Baked} position={[1.469, 0.727, -29.325]} />
      <mesh geometry={nodes.MousePad_Baked.geometry} material={newMaterials.MousePad_Baked} position={[1.499, 0.721, -28.525]} />
      <mesh geometry={nodes.Iphone_Baked.geometry} material={newMaterials.Iphone_Baked} position={[1.588, 0.727, -28.151]} />
      <mesh geometry={nodes.CottonVase_Baked.geometry} material={newMaterials.CottonVase_Baked} position={[1.093, 0.72, -27.974]} />
      <mesh geometry={nodes.PowerBank_Baked.geometry} material={newMaterials.PowerBank_Baked} position={[1.303, 0.729, -27.973]} />
      <mesh geometry={nodes.Decorative_vase_with_branches001_Baked.geometry} material={newMaterials['Decorative vase with branches.001_Baked']} position={[1.133, 0.981, -29.361]} rotation={[0, 0.663, 0]} />
      <mesh geometry={nodes.Tulips_Baked.geometry} material={newMaterials.Tulips_Baked} position={[1.386, 0.835, -29.439]} />
      <group position={[0.646, 0.783, -27.997]}>
        <mesh geometry={nodes.LAMP_SHADE_GRAY001.geometry} material={newMaterials.LAMP_SHADE_GRAY_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_1.geometry} material={newMaterials.DialPhone_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_2.geometry} material={newMaterials.Tablet_blinn2_0_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_3.geometry} material={newMaterials.Pidgey_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_4.geometry} material={newMaterials.NotebookPen_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_5.geometry} material={newMaterials.Monitor_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_6.geometry} material={newMaterials.DeskClock_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_7.geometry} material={newMaterials.Keyboard_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_8.geometry} material={newMaterials.CatLamp_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_9.geometry} material={newMaterials.Mouse_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_10.geometry} material={newMaterials.PencilHolder_Baked} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_11.geometry} material={newMaterials['WoodCoaster.011_Baked']} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_12.geometry} material={newMaterials['Coffee mug n5_Baked']} />
        <mesh geometry={nodes.LAMP_SHADE_GRAY001_13.geometry} material={newMaterials['Circle_Material.002_0_Baked']} />
      </group>
      <group position={[1.244, 2.56, -32.515]}>
        <mesh geometry={nodes.Circle010.geometry} material={newMaterials['Antler trophy display_Baked']} />
        <mesh geometry={nodes.Circle010_1.geometry} material={newMaterials.Floor_Baked} />
        <mesh geometry={nodes.Circle010_2.geometry} material={newMaterials.Walls_Baked} />
      </group>
      <mesh ref={fanRef} geometry={nodes.LAMP_SHADE_GRAY_Baked001.geometry} material={newMaterials['Circle_Material.002_0_Baked']} position={[1.59, 0.817, -29.473]} />
      <mesh geometry={nodes.LaptopScreen_Baked.geometry} material={newMaterials['LaptopScreen_Baked.001']} position={[1.469, 0.727, -29.325]} />
    </group>
  )
}

useGLTF.preload('/Light1stoffice.glb')
