/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light5thoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Light5thoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[-0.671, 0.592, -32.151]}>
        <mesh geometry={nodes.Object_2007.geometry} material={newMaterials.CattoBed_Baked} />
        <mesh geometry={nodes.Object_2007_1.geometry} material={newMaterials.CatTree_Baked} />
        <mesh geometry={nodes.Object_2007_2.geometry} material={newMaterials.Catto_Baked} />
        <mesh geometry={nodes.Object_2007_3.geometry} material={newMaterials.PetBowl_Baked} />
        <mesh geometry={nodes.Object_2007_4.geometry} material={newMaterials.CatHouse_Baked} />
        <mesh geometry={nodes.Object_2007_5.geometry} material={newMaterials.CatScratch_Baked} />
        <mesh geometry={nodes.Object_2007_6.geometry} material={newMaterials['Panier chat_Baked']} />
        <mesh geometry={nodes.Object_2007_7.geometry} material={newMaterials['Tapis 22_Baked.002']} />
      </group>
      <group position={[-2.167, 0.578, -32.202]}>
        <mesh geometry={nodes.Circle007.geometry} material={newMaterials.ModularPot_Baked} />
        <mesh geometry={nodes.Circle007_1.geometry} material={newMaterials.FEUILLE_Baked} />
        <mesh geometry={nodes.Circle007_2.geometry} material={newMaterials.FEUILLE2_Baked} />
      </group>
      <mesh geometry={nodes.Vase_Baked.geometry} material={newMaterials.Vase_Baked} position={[-1.698, 0.276, -32.201]} />
      <group position={[-2.104, 0.59, -30.948]}>
        <mesh geometry={nodes.Cylinder013_silverball_record_0001.geometry} material={newMaterials.VinylPlayer_Baked} />
        <mesh geometry={nodes.Cylinder013_silverball_record_0001_1.geometry} material={newMaterials.Bambino_Baked} />
        <mesh geometry={nodes.Cylinder013_silverball_record_0001_2.geometry} material={newMaterials.Radio_Baked} />
        <mesh geometry={nodes.Cylinder013_silverball_record_0001_3.geometry} material={newMaterials['BohoTable_Baked.001']} />
        <mesh geometry={nodes.Cylinder013_silverball_record_0001_4.geometry} material={newMaterials['WhiteGuitar_Baked.001']} />
      </group>
      <mesh geometry={nodes.WallCabinet_Baked.geometry} material={newMaterials.WallCabinet_Baked} position={[-2.384, 0.347, -29.011]} />
      <group position={[-1.718, 0.612, -32.203]}>
        <mesh geometry={nodes.Mesh009.geometry} material={newMaterials['Fiber stick_Baked']} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={newMaterials.Leaves_Baked} />
      </group>
    </group>
  )
}

useGLTF.preload('/Light5thoffice.glb')
