/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light2ndoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Light2ndoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PlasticBox_Baked.geometry} material={newMaterials.PlasticBox_Baked} position={[1.287, 0.227, -30.716]} />
      <mesh geometry={nodes.Kilim_carpet_Baked.geometry} material={newMaterials['Kilim carpet_Baked']} position={[1.157, 0.133, -30.827]} />
      <group position={[2.725, 0.318, -31.906]}>
        <mesh geometry={nodes.Mesh007.geometry} material={newMaterials.SmallCouchPlant_Baked} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={newMaterials.PlantCouch_Baked} />
      </group>
      <mesh geometry={nodes.Big_Monstera_plant_Baked.geometry} material={newMaterials['Big Monstera plant_Baked']} position={[2.414, 0.132, -32.22]} />
      <mesh geometry={nodes.WhiteSofa_Baked.geometry} material={newMaterials.WhiteSofa_Baked} position={[0.621, 0.672, -32.092]} />
      <group position={[0.32, 0.602, -31.843]}>
        <mesh geometry={nodes.blanket_02_blanket_0001.geometry} material={newMaterials.ArmRestBlanket_Baked} />
        <mesh geometry={nodes.blanket_02_blanket_0001_1.geometry} material={newMaterials.FoldBlanket_Baked} />
        <mesh geometry={nodes.blanket_02_blanket_0001_2.geometry} material={newMaterials.WindowBush2_Baked} />
      </group>
      <mesh geometry={nodes.PillowSofa1_Baked.geometry} material={newMaterials.PillowSofa1_Baked} position={[0.621, 0.672, -32.092]} />
      <group position={[1.419, 0.697, -32.135]}>
        <mesh geometry={nodes.Plane019.geometry} material={newMaterials['Pattern cushion-D_Baked']} />
        <mesh geometry={nodes.Plane019_1.geometry} material={newMaterials['Round Pillow_Baked']} />
        <mesh geometry={nodes.Plane019_2.geometry} material={newMaterials['Linen rustic pillow-02_Baked']} />
      </group>
      <mesh geometry={nodes.PillowSofa2_Baked.geometry} material={newMaterials.PillowSofa2_Baked} position={[0.621, 0.672, -32.092]} />
      <mesh geometry={nodes.LovePillow003_Baked.geometry} material={newMaterials['LovePillow.003_Baked']} position={[0.728, 0.583, -31.908]} />
      <mesh geometry={nodes.sweater_FIX_Baked.geometry} material={newMaterials.sweater_FIX_Baked} position={[0.983, 0.545, -31.863]} />
      <group position={[0.983, 0.697, -32.166]}>
        <mesh geometry={nodes['302161597_002001'].geometry} material={newMaterials.Almofada_baked} />
        <mesh geometry={nodes['302161597_002001_1'].geometry} material={newMaterials['Almofada estampa B']} />
        <mesh geometry={nodes['302161597_002001_2'].geometry} material={newMaterials['Linha preta']} />
      </group>
      <group position={[1.215, 2.134, -32.508]}>
        <mesh geometry={nodes.Long_curtain001.geometry} material={newMaterials['Long curtain_Baked']} />
        <mesh geometry={nodes.Long_curtain001_1.geometry} material={newMaterials.WindowPlant_Baked} />
        <mesh geometry={nodes.Long_curtain001_2.geometry} material={newMaterials['Succulent plant_Baked']} />
        <mesh geometry={nodes.Long_curtain001_3.geometry} material={newMaterials.WindowBush1_Baked} />
      </group>
      <group position={[1.237, 0.138, -30.766]}>
        <mesh geometry={nodes.Plane010.geometry} material={newMaterials.Minimalist_Coffee_Table_Baked} />
        <mesh geometry={nodes.Plane010_1.geometry} material={newMaterials.PampassGrass_Baked} />
        <mesh geometry={nodes.Plane010_2.geometry} material={newMaterials['Ceramic and golden vase_Baked']} />
        <mesh geometry={nodes.Plane010_3.geometry} material={newMaterials['Ceramic Pampass_Baked']} />
        <mesh geometry={nodes.Plane010_4.geometry} material={newMaterials.Magazine2_Baked} />
        <mesh geometry={nodes.Plane010_5.geometry} material={newMaterials.Magazines_Baked} />
        <mesh geometry={nodes.Plane010_6.geometry} material={newMaterials.wicker_basket_01_Baked} />
        <mesh geometry={nodes.Plane010_7.geometry} material={newMaterials.Hopi_Baked} />
      </group>
    </group>
  )
}

useGLTF.preload('/Light2ndoffice.glb')
