/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light4thoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Light4thoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);
  
  return (
    <group {...props} dispose={null}>
      <group position={[-2.237, 1.085, -32.266]}>
        <mesh geometry={nodes.Object_0027.geometry} material={newMaterials.mariobake} />
        <mesh geometry={nodes.Object_0027_1.geometry} material={newMaterials.bonniebake} />
        <mesh geometry={nodes.Object_0027_2.geometry} material={newMaterials.capbake} />
        <mesh geometry={nodes.Object_0027_3.geometry} material={newMaterials.chicabake} />
        <mesh geometry={nodes.Object_0027_4.geometry} material={newMaterials.falloutbake} />
        <mesh geometry={nodes.Object_0027_5.geometry} material={newMaterials.foxybake} />
        <mesh geometry={nodes.Object_0027_6.geometry} material={newMaterials.fredbake} />
        <mesh geometry={nodes.Object_0027_7.geometry} material={newMaterials.ironmanbake} />
        <mesh geometry={nodes.Object_0027_8.geometry} material={newMaterials.sansbake} />
        <mesh geometry={nodes.Object_0027_9.geometry} material={newMaterials.spiderbake} />
        <mesh geometry={nodes.Object_0027_10.geometry} material={newMaterials.DrStrange_baked_Baked} />
      </group>
      <group position={[-2.23, 2.22, -32.362]}>
        <mesh geometry={nodes.Plano003.geometry} material={newMaterials['Asplenium Nidu Plant.001_Baked']} />
        <mesh geometry={nodes.Plano003_1.geometry} material={newMaterials.aspleniumpotbaked} />
      </group>
      <group position={[-2.563, 1.993, -28.706]}>
        <mesh geometry={nodes.Plane030.geometry} material={newMaterials.WoodenBox_Baked} />
        <mesh geometry={nodes.Plane030_1.geometry} material={newMaterials.ShelfBasket_Baked} />
        <mesh geometry={nodes.Plane030_2.geometry} material={newMaterials['White vase.001_Baked']} />
        <mesh geometry={nodes.Plane030_3.geometry} material={newMaterials.VinylStack_Baked} />
        <mesh geometry={nodes.Plane030_4.geometry} material={newMaterials.VinylStack3_Baked} />
        <mesh geometry={nodes.Plane030_5.geometry} material={newMaterials.ToyPlane_Baked} />
        <mesh geometry={nodes.Plane030_6.geometry} material={newMaterials.VinylStack2_Baked} />
        <mesh geometry={nodes.Plane030_7.geometry} material={newMaterials.BornToDie_Baked} />
        <mesh geometry={nodes.Plane030_8.geometry} material={newMaterials.shelves_baked} />
      </group>
      <mesh geometry={nodes.BookStack4_Baked.geometry} material={newMaterials.BooksMerge_Baked} position={[-2.609, 1.615, -30.042]} />
      <group position={[-2.565, 1.944, -29.972]}>
        <mesh geometry={nodes.Maillage016.geometry} material={newMaterials.stackbooks_bake} />
        <mesh geometry={nodes.Maillage016_1.geometry} material={newMaterials.stackofbooks2_bake} />
      </group>
      <mesh geometry={nodes.CornerShelf_Bake.geometry} material={newMaterials['Material.082']} position={[-2.271, 1.532, -32.398]} />
      <mesh geometry={nodes.Magz_Sub_bake.geometry} material={newMaterials.Magz_bake} position={[-2.502, 1.638, -28.751]} />
    </group>
  )
}

useGLTF.preload('/Light4thoffice.glb')
