/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light3rdoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Light3rdoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[-2.349, 1.938, -29.509]}>
        <mesh geometry={nodes.Tessellation002_Material028_0002.geometry} material={newMaterials['WallPlate2.002_Baked']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_1.geometry} material={newMaterials.Strawhat_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_2.geometry} material={newMaterials.StrawhatNR_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_3.geometry} material={newMaterials.Wallplates_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_4.geometry} material={newMaterials.DreamCatcher1_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_5.geometry} material={newMaterials.UltraDreamCatcher_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_6.geometry} material={newMaterials['photo-14']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_7.geometry} material={newMaterials.frame} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_8.geometry} material={newMaterials.glass} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_9.geometry} material={newMaterials['photo-7']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_10.geometry} material={newMaterials['frame.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_11.geometry} material={newMaterials['glass.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_12.geometry} material={newMaterials.VividBoho_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_13.geometry} material={newMaterials['Botanicboho_Baked.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_14.geometry} material={newMaterials['LunarBoho_Baked.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_15.geometry} material={newMaterials['MountainBoho_Baked.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_16.geometry} material={newMaterials.WallClock_Baked} />
      </group>
      <group position={[-1.387, 1.674, -31.867]}>
        <mesh geometry={nodes.Object_62007.geometry} material={newMaterials.Macrame2_Baked} />
        <mesh geometry={nodes.Object_62007_1.geometry} material={newMaterials['Macrame1_Baked.001']} />
        <mesh geometry={nodes.Object_62007_2.geometry} material={newMaterials.MacrameWood2_Baked} />
      </group>
    </group>
  )
}

useGLTF.preload('/Light3rdoffice.glb')
