/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lighttargets.glb 
*/

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';
import gsap from 'gsap';

export default function Model(props) {
  const { nodes } = useGLTF('/models/lighttargets.glb')

  const blackMaterial = new THREE.MeshBasicMaterial({ color: 'black' });

  const aboutAnimRef = useRef();
  const projectsAnimRef = useRef();
  const skillsAnimRef = useRef();
  const contactsAnimRef = useRef();

  const animationPairs = {
    "About_Hitbox": {ref: aboutAnimRef},
    "Projects_Hitbox": {ref: projectsAnimRef},
    "Skills_Hitbox": {ref: skillsAnimRef},
    "Contacts_Hitbox": {ref: contactsAnimRef},
  }

  const onHover = (key, isHovering) => {
    const animObject = animationPairs[key];
    gsap.to(animObject.ref.current.scale, {
      x: isHovering ? 1 : 0,
      y: isHovering ? 1 : 0,
      z: isHovering ? 1 : 0,
      duration: 0.5,
      ease: "power2.out",
    })
  }

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.About_Hitbox.geometry} 
        material={nodes.About_Hitbox.material}
        visible={false} 
        position={[1.674, 0.584, -28.723]} 
        onPointerOver={() => {
          onHover("About_Hitbox", true);
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={() => {
          onHover("About_Hitbox", false)
          document.body.style.cursor = "auto";
        }}
      />
      <mesh 
        ref={aboutAnimRef}
        geometry={nodes.About_Hitbox_Anim.geometry} 
        material={blackMaterial} 
        scale={[0, 0, 0]}
        position={[1.674, 0.584, -28.723]} 
      />
      <mesh 
        geometry={nodes.Projects_Hitbox.geometry} 
        material={nodes.Projects_Hitbox.material} 
        visible={false} 
        position={[-2.289, 1.632, -29.336]} 
        onPointerOver={() => {
          onHover("Projects_Hitbox", true);
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={() => {
          onHover("Projects_Hitbox", false)
          document.body.style.cursor = "auto";
        }}
      />
      <mesh 
        ref={projectsAnimRef}
        geometry={nodes.Projects_Hitbox_Anim.geometry} 
        material={blackMaterial} 
        scale={[0, 0, 0]}
        position={[-2.289, 1.632, -29.336]} 
      />
      <mesh 
        geometry={nodes.Skills_Hitbox.geometry} 
        material={nodes.Skills_Hitbox.material} 
        visible={false} 
        position={[-2.134, 0.494, -31.226]} 
        onPointerOver={() => {
          onHover("Skills_Hitbox", true);
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={() => {
          onHover("Skills_Hitbox", false)
          document.body.style.cursor = "auto";
        }}
      />
      <mesh 
        ref={skillsAnimRef}
        geometry={nodes.Skills_Hitbox_Anim.geometry} 
        material={blackMaterial} 
        scale={[0, 0, 0]}
        position={[-2.134, 0.494, -31.226]} 
      />
      <mesh 
        geometry={nodes.Contacts_Hitbox.geometry} 
        material={nodes.Contacts_Hitbox.material} 
        visible={false} 
        position={[1.396, 0.691, -31.847]} 
        onPointerOver={() => {
          onHover("Contacts_Hitbox", true);
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={() => {
          onHover("Contacts_Hitbox", false)
          document.body.style.cursor = "auto";
        }}
      />
      <mesh 
        ref={contactsAnimRef}
        geometry={nodes.Contacts_Hitbox_Anim.geometry} 
        material={blackMaterial} 
        scale={[0, 0, 0]}
        position={[1.396, 0.691, -31.847]} 
      />
    </group>
  )
}

useGLTF.preload('/lighttargets.glb')
