/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lighthomeoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/lighthomeoffice.glb')

  console.log(nodes);
        
  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Backdrop_Baked.geometry} material={newMaterials['Backdrop_Baked.003']} position={[0, -0.01, -29.962]} />
      <mesh geometry={nodes.RattanTrashcan_Baked.geometry} material={newMaterials.RattanTrashcan_Baked} position={[1.605, 0.197, -27.689]} />
      <mesh geometry={nodes.Monitor_Baked.geometry} material={newMaterials.Monitor_Baked} position={[1.192, 1.027, -28.372]} />
      <mesh geometry={nodes.MousePad_Baked.geometry} material={newMaterials.MousePad_Baked} position={[1.499, 0.721, -28.489]} />
      <group position={[1.55, 0.726, -28.095]}>
        <mesh geometry={nodes.Cube011.geometry} material={newMaterials.Iphone_Baked} />
        <mesh geometry={nodes.Cube011_1.geometry} material={newMaterials.PowerBank_Baked} />
      </group>
      <mesh geometry={nodes.CottonVase_Baked.geometry} material={newMaterials.CottonVase_Baked} position={[1.107, 0.955, -27.949]} />
      <mesh geometry={nodes.Decorative_vase_with_branches001_Baked.geometry} material={newMaterials['Decorative vase with branches.001_Baked']} position={[1.133, 0.981, -29.324]} />
      <mesh geometry={nodes.Tulips_Baked.geometry} material={newMaterials.Tulips_Baked} position={[1.411, 0.825, -29.409]} />
      <group position={[1.505, 0.729, -28.246]}>
        <mesh geometry={nodes.Phone001.geometry} material={newMaterials.DialPhone_Baked} />
        <mesh geometry={nodes.Phone001_1.geometry} material={newMaterials.BinderStacks_Baked} />
        <mesh geometry={nodes.Phone001_2.geometry} material={newMaterials.Tablet_blinn2_0_Baked} />
        <mesh geometry={nodes.Phone001_3.geometry} material={newMaterials.Pidgey_Baked} />
        <mesh geometry={nodes.Phone001_4.geometry} material={newMaterials['Circle_Material.002_0_Baked']} />
        <mesh geometry={nodes.Phone001_5.geometry} material={newMaterials['WoodCoaster.011_Baked']} />
        <mesh geometry={nodes.Phone001_6.geometry} material={newMaterials.Keyboard_Baked} />
        <mesh geometry={nodes.Phone001_7.geometry} material={newMaterials.Mouse_Baked} />
        <mesh geometry={nodes.Phone001_8.geometry} material={newMaterials.CatLamp_Baked} />
        <mesh geometry={nodes.Phone001_9.geometry} material={newMaterials.NotebookPen_Baked} />
        <mesh geometry={nodes.Phone001_10.geometry} material={newMaterials.PencilHolder_Baked} />
        <mesh geometry={nodes.Phone001_11.geometry} material={newMaterials.DeskClock_Baked} />
        <mesh geometry={nodes.Phone001_12.geometry} material={newMaterials['Coffee mug n5_Baked']} />
      </group>
      <group position={[1.123, 0.607, -30.712]}>
        <mesh geometry={nodes.Vert002.geometry} material={newMaterials.wicker_basket_01_Baked} />
        <mesh geometry={nodes.Vert002_1.geometry} material={newMaterials.Minimalist_Coffee_Table_Baked} />
        <mesh geometry={nodes.Vert002_2.geometry} material={newMaterials.Magazine2_Baked} />
        <mesh geometry={nodes.Vert002_3.geometry} material={newMaterials.Magazines_Baked} />
        <mesh geometry={nodes.Vert002_4.geometry} material={newMaterials.PampassGrass_Baked} />
        <mesh geometry={nodes.Vert002_5.geometry} material={newMaterials['Ceramic and golden vase_Baked']} />
        <mesh geometry={nodes.Vert002_6.geometry} material={newMaterials['Ceramic Pampass_Baked']} />
        <mesh geometry={nodes.Vert002_7.geometry} material={newMaterials.Hopi_Baked} />
      </group>
      <mesh geometry={nodes.Folded_garment_stack_Baked.geometry} material={newMaterials['Folded garment stack_Baked']} position={[0.913, 0.25, -30.66]} />
      <mesh geometry={nodes.PlasticBox_Baked.geometry} material={newMaterials.PlasticBox_Baked} position={[1.442, 0.255, -30.678]} />
      <mesh geometry={nodes.Kilim_carpet_Baked.geometry} material={newMaterials['Kilim carpet_Baked']} position={[1.169, 0.138, -30.806]} />
      <group position={[2.437, 0.495, -31.776]}>
        <mesh geometry={nodes.Mesh006.geometry} material={newMaterials.PlantCouch_Baked} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={newMaterials.SmallCouchPlant_Baked} />
      </group>
      <mesh geometry={nodes.Big_Monstera_plant_Baked.geometry} material={newMaterials['Big Monstera plant_Baked']} position={[2.41, 0.604, -32.183]} />
      <mesh geometry={nodes.WhiteSofa_Baked.geometry} material={newMaterials.WhiteSofa_Baked} position={[1.211, 0.551, -32.169]} />
      <group position={[1.193, 0.554, -31.918]}>
        <mesh geometry={nodes.blanket_02_blanket_0001.geometry} material={newMaterials.ArmRestBlanket_Baked} />
        <mesh geometry={nodes.blanket_02_blanket_0001_1.geometry} material={newMaterials.FoldBlanket_Baked} />
      </group>
      <mesh geometry={nodes.PillowSofa1_Baked.geometry} material={newMaterials.PillowSofa1_Baked} position={[0.632, 0.682, -32.065]} />
      <mesh geometry={nodes.Pattern_cushion_Baked.geometry} material={newMaterials['Pattern cushion-D_Baked']} position={[1.42, 0.677, -32.159]} />
      <mesh geometry={nodes.PillowSofa2_Baked.geometry} material={newMaterials.PillowSofa2_Baked} position={[1.788, 0.669, -32.062]} />
      <mesh geometry={nodes.LovePillow003_Baked.geometry} material={newMaterials['LovePillow.003_Baked']} position={[0.717, 0.605, -31.904]} />
      <group position={[1.079, 0.595, -31.956]}>
        <mesh geometry={nodes.Plane021.geometry} material={newMaterials['Round Pillow_Baked']} />
        <mesh geometry={nodes.Plane021_1.geometry} material={newMaterials['Linen rustic pillow-02_Baked']} />
        <mesh geometry={nodes.Plane021_2.geometry} material={newMaterials.sweater_FIX_Baked} />
      </group>
      <group position={[1.028, 0.68, -32.133]}>
        <mesh geometry={nodes['302161597_002001'].geometry} material={newMaterials.Almofada_baked} />
        <mesh geometry={nodes['302161597_002001_1'].geometry} material={newMaterials['Almofada estampa B']} />
        <mesh geometry={nodes['302161597_002001_2'].geometry} material={newMaterials['Linha preta']} />
      </group>
      <group position={[1.211, 1.231, -32.472]}>
        <mesh geometry={nodes.Object_0020.geometry} material={newMaterials.WindowPlant_Baked} />
        <mesh geometry={nodes.Object_0020_1.geometry} material={newMaterials['Succulent plant_Baked']} />
        <mesh geometry={nodes.Object_0020_2.geometry} material={newMaterials.WindowBush1_Baked} />
        <mesh geometry={nodes.Object_0020_3.geometry} material={newMaterials['Long curtain_Baked']} />
      </group>
      <mesh geometry={nodes.WindowBush2_Baked.geometry} material={newMaterials.WindowBush2_Baked} position={[0.851, 0.866, -32.557]} />
      <group position={[-0.671, 0.592, -32.114]}>
        <mesh geometry={nodes.Object_2007.geometry} material={newMaterials.CattoBed_Baked} />
        <mesh geometry={nodes.Object_2007_1.geometry} material={newMaterials.CatTree_Baked} />
        <mesh geometry={nodes.Object_2007_2.geometry} material={newMaterials.Catto_Baked} />
        <mesh geometry={nodes.Object_2007_3.geometry} material={newMaterials.PetBowl_Baked} />
        <mesh geometry={nodes.Object_2007_4.geometry} material={newMaterials.CatHouse_Baked} />
        <mesh geometry={nodes.Object_2007_5.geometry} material={newMaterials.CatScratch_Baked} />
        <mesh geometry={nodes.Object_2007_6.geometry} material={newMaterials['Panier chat_Baked']} />
        <mesh geometry={nodes.Object_2007_7.geometry} material={newMaterials['Tapis 22_Baked.002']} />
      </group>
      <group position={[-1.46, 2.502, -32.336]}>
        <mesh geometry={nodes.Maillage008.geometry} material={newMaterials.basilPot_Baked} />
        <mesh geometry={nodes.Maillage008_1.geometry} material={newMaterials.basil_Baked} />
      </group>
      <group position={[-1.818, 2.235, -30.915]}>
        <mesh geometry={nodes.grass_lambert9_0002.geometry} material={newMaterials.ShelvePlant1Pot_Baked} />
        <mesh geometry={nodes.grass_lambert9_0002_1.geometry} material={newMaterials.ShelvePlant1_Baked} />
      </group>
      <mesh geometry={nodes.ShelvePlant3_Baked.geometry} material={newMaterials.ShelvePlant3_Baked} position={[-1.142, 2.004, -32.37]} />
      <group position={[-2.167, 0.578, -32.165]}>
        <mesh geometry={nodes.Circle007.geometry} material={newMaterials.ModularPot_Baked} />
        <mesh geometry={nodes.Circle007_1.geometry} material={newMaterials.FEUILLE_Baked} />
        <mesh geometry={nodes.Circle007_2.geometry} material={newMaterials.FEUILLE2_Baked} />
      </group>
      <mesh geometry={nodes.Vase_Baked.geometry} material={newMaterials.Vase_Baked} position={[-1.698, 0.276, -32.163]} />
      <group position={[-1.797, 1.252, -30.679]}>
        <mesh geometry={nodes.Plane029.geometry} material={newMaterials.BookshelfPlantPot_Baked} />
        <mesh geometry={nodes.Plane029_1.geometry} material={newMaterials.BookshelfPlant_Baked} />
      </group>
      <mesh geometry={nodes.CornerShelf_baked.geometry} material={newMaterials.cornershelfbaked} position={[-2.267, 1.556, -32.357]} />
      <group position={[-2.233, 1.557, -32.315]}>
        <mesh geometry={nodes.Object_0027.geometry} material={newMaterials.mariobake} />
        <mesh geometry={nodes.Object_0027_1.geometry} material={newMaterials.falloutbake} />
        <mesh geometry={nodes.Object_0027_2.geometry} material={newMaterials.sansbake} />
        <mesh geometry={nodes.Object_0027_3.geometry} material={newMaterials.chicabake} />
        <mesh geometry={nodes.Object_0027_4.geometry} material={newMaterials.bonniebake} />
        <mesh geometry={nodes.Object_0027_5.geometry} material={newMaterials.foxybake} />
        <mesh geometry={nodes.Object_0027_6.geometry} material={newMaterials.fredbake} />
        <mesh geometry={nodes.Object_0027_7.geometry} material={newMaterials.ironmanbake} />
        <mesh geometry={nodes.Object_0027_8.geometry} material={newMaterials.capbake} />
        <mesh geometry={nodes.Object_0027_9.geometry} material={newMaterials.spiderbake} />
        <mesh geometry={nodes.Object_0027_10.geometry} material={newMaterials.DrStrange_baked_Baked} />
      </group>
      <group position={[-2.23, 2.222, -32.326]}>
        <mesh geometry={nodes.Plano003.geometry} material={newMaterials['Asplenium Nidu Plant.001_Baked']} />
        <mesh geometry={nodes.Plano003_1.geometry} material={newMaterials.aspleniumpotbaked} />
      </group>
      <group position={[-2.104, 0.59, -30.911]}>
        <mesh geometry={nodes.Cylinder013_silverball_record_0001.geometry} material={newMaterials.VinylPlayer_Baked} />
        <mesh geometry={nodes.Cylinder013_silverball_record_0001_1.geometry} material={newMaterials.Bambino_Baked} />
        <mesh geometry={nodes.Cylinder013_silverball_record_0001_2.geometry} material={newMaterials.Radio_Baked} />
        <mesh geometry={nodes.Cylinder013_silverball_record_0001_3.geometry} material={newMaterials['BohoTable_Baked.001']} />
        <mesh geometry={nodes.Cylinder013_silverball_record_0001_4.geometry} material={newMaterials['WhiteGuitar_Baked.001']} />
      </group>
      <group position={[-2.31, 1.24, -30.582]}>
        <mesh geometry={nodes.Maillage009.geometry} material={newMaterials['Stack of books.002_Baked']} />
        <mesh geometry={nodes.Maillage009_1.geometry} material={newMaterials['Stack of books_Baked']} />
      </group>
      <group position={[-2.349, 1.938, -29.472]}>
        <mesh geometry={nodes.Tessellation002_Material028_0002.geometry} material={newMaterials['WallPlate2.002_Baked']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_1.geometry} material={newMaterials.Strawhat_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_2.geometry} material={newMaterials.StrawhatNR_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_3.geometry} material={newMaterials.Wallplates_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_4.geometry} material={newMaterials.DreamCatcher1_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_5.geometry} material={newMaterials.UltraDreamCatcher_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_6.geometry} material={newMaterials['photo-14']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_7.geometry} material={newMaterials.frame} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_8.geometry} material={newMaterials.glass} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_9.geometry} material={newMaterials['photo-7']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_10.geometry} material={newMaterials['frame.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_11.geometry} material={newMaterials['glass.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_12.geometry} material={newMaterials.VividBoho_Baked} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_13.geometry} material={newMaterials['Botanicboho_Baked.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_14.geometry} material={newMaterials['LunarBoho_Baked.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_15.geometry} material={newMaterials['MountainBoho_Baked.001']} />
        <mesh geometry={nodes.Tessellation002_Material028_0002_16.geometry} material={newMaterials.WallClock_Baked} />
      </group>
      <mesh geometry={nodes.WallCabinet_Baked.geometry} material={newMaterials.WallCabinet_Baked} position={[-2.384, 0.347, -28.974]} />
      <mesh geometry={nodes.WoodenBox_Baked.geometry} material={newMaterials.WoodenBox_Baked} position={[-2.593, 2.024, -28.67]} />
      <group position={[-2.285, 1.265, -30.277]}>
        <mesh geometry={nodes.Object_1003.geometry} material={newMaterials.BornToDie_Baked} />
        <mesh geometry={nodes.Object_1003_1.geometry} material={newMaterials.VinylStack2_Baked} />
        <mesh geometry={nodes.Object_1003_2.geometry} material={newMaterials.VinylStack_Baked} />
        <mesh geometry={nodes.Object_1003_3.geometry} material={newMaterials.VinylStack3_Baked} />
        <mesh geometry={nodes.Object_1003_4.geometry} material={newMaterials['Hand made clay vase.001_Baked']} />
        <mesh geometry={nodes.Object_1003_5.geometry} material={newMaterials['ShelvesRight.001_Baked']} />
        <mesh geometry={nodes.Object_1003_6.geometry} material={newMaterials.StrawVase_Baked} />
        <mesh geometry={nodes.Object_1003_7.geometry} material={newMaterials.ToyPlane_Baked} />
        <mesh geometry={nodes.Object_1003_8.geometry} material={newMaterials.ShelfBasket_Baked} />
        <mesh geometry={nodes.Object_1003_9.geometry} material={newMaterials['White vase.001_Baked']} />
        <mesh geometry={nodes.Object_1003_10.geometry} material={newMaterials.Shelves_Baked} />
        <mesh geometry={nodes.Object_1003_11.geometry} material={newMaterials.UpBooks_Baked} />
        <mesh geometry={nodes.Object_1003_12.geometry} material={newMaterials.Magz_Sub_Baked} />
        <mesh geometry={nodes.Object_1003_13.geometry} material={newMaterials.BookStack1_Baked} />
        <mesh geometry={nodes.Object_1003_14.geometry} material={newMaterials.Bookstack7_Baked} />
        <mesh geometry={nodes.Object_1003_15.geometry} material={newMaterials.BookStack2_Baked} />
        <mesh geometry={nodes.Object_1003_16.geometry} material={newMaterials.BookStack4_Baked} />
        <mesh geometry={nodes.Object_1003_17.geometry} material={newMaterials.Photography_Baked} />
        <mesh geometry={nodes.Object_1003_18.geometry} material={newMaterials.Bookstack6_Baked} />
        <mesh geometry={nodes.Object_1003_19.geometry} material={newMaterials.BookStack3_Baked} />
        <mesh geometry={nodes.Object_1003_20.geometry} material={newMaterials.Bookstack5_Baked} />
      </group>
      <group position={[1.24, 2.642, -32.393]}>
        <mesh geometry={nodes.Cube041.geometry} material={newMaterials.Walls_Baked} />
        <mesh geometry={nodes.Cube041_1.geometry} material={newMaterials.Floor_Baked} />
        <mesh geometry={nodes.Cube041_2.geometry} material={newMaterials.WindowFrame_Baked} />
        <mesh geometry={nodes.Cube041_3.geometry} material={newMaterials['Antler trophy display_Baked']} />
      </group>
      <group position={[-1.193, 0.615, -28.033]}>
        <mesh geometry={nodes.Object_0034.geometry} material={newMaterials.Canvas_Baked} />
        <mesh geometry={nodes.Object_0034_1.geometry} material={newMaterials['Canvas painting_Baked']} />
        <mesh geometry={nodes.Object_0034_2.geometry} material={newMaterials.Saoirse_Baked} />
        <mesh geometry={nodes.Object_0034_3.geometry} material={newMaterials['Easel.001_Baked']} />
        <mesh geometry={nodes.Object_0034_4.geometry} material={newMaterials.Paintbrushes_Baked} />
        <mesh geometry={nodes.Object_0034_5.geometry} material={newMaterials.Palette_Baked} />
        <mesh geometry={nodes.Object_0034_6.geometry} material={newMaterials.Stool_Baked} />
      </group>
      <mesh geometry={nodes.CornerPlant2_Baked.geometry} material={newMaterials.CornerPlant2_Baked} position={[-1.995, 0.445, -27.554]} />
      <mesh geometry={nodes.CornerPlant2pot_Baked.geometry} material={newMaterials.CornerPlant2pot_Baked} position={[-1.988, 0.248, -27.581]} />
      <mesh geometry={nodes.Round_embossed_flower_carpet_Baked.geometry} material={newMaterials['Round embossed flower carpet_Baked']} position={[-0.818, 0.136, -28.135]} />
      <mesh geometry={nodes.LAMP_SHADE_GRAY_Baked.geometry} material={newMaterials.LAMP_SHADE_GRAY_Baked} position={[0.646, 0.638, -27.961]} />
      <mesh geometry={nodes.PillowBasket_Baked.geometry} material={newMaterials.PillowBasket_Baked} position={[-0.047, 0.265, -30.869]} />
      <mesh geometry={nodes.Rattan_Knot_Chair2_Baked001.geometry} material={newMaterials['Rattan Knot Chair.001_Baked']} position={[-0.439, 0.377, -29.757]} />
      <mesh geometry={nodes.cowrug_Baked.geometry} material={newMaterials['peau de vache_Baked.001']} position={[-0.892, 0.142, -29.768]} />
      <group position={[-1.387, 1.674, -31.83]}>
        <mesh geometry={nodes.Object_62007.geometry} material={newMaterials.Macrame2_Baked} />
        <mesh geometry={nodes.Object_62007_1.geometry} material={newMaterials['Macrame1_Baked.001']} />
        <mesh geometry={nodes.Object_62007_2.geometry} material={newMaterials.MacrameWood2_Baked} />
      </group>
      <mesh geometry={nodes.MacrameWood_Baked.geometry} material={newMaterials.MacrameWood_Baked} position={[-2.378, 1.93, -31.175]} />
      <mesh geometry={nodes.Laptop_Baked.geometry} material={newMaterials.Laptop_Baked} position={[1.365, 0.738, -29.152]} />
      <group position={[1.842, 0.456, -28.588]}>
        <mesh geometry={nodes.pCube209_slipa_0031.geometry} material={newMaterials.Slippers_Baked} />
        <mesh geometry={nodes.pCube209_slipa_0031_1.geometry} material={newMaterials['Desk Top_Baked']} />
        <mesh geometry={nodes.pCube209_slipa_0031_2.geometry} material={newMaterials.RattanCompchair_Baked} />
      </group>
      <mesh geometry={nodes.UnderBasket_Baked.geometry} material={newMaterials['UnderBasket_Baked.001']} position={[1.408, 0.447, -29.287]} />
      <mesh geometry={nodes.MonitorScreen.geometry} material={newMaterials.Monitor_Baked} position={[1.246, 0.99, -28.373]} />
      <mesh geometry={nodes.LaptopScreen.geometry} material={newMaterials.Laptop_Baked} position={[1.326, 0.824, -29.225]} />
      <group position={[-1.718, 0.612, -32.165]}>
        <mesh geometry={nodes.Mesh009.geometry} material={newMaterials['Fiber stick_Baked']} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={newMaterials.Leaves_Baked} />
      </group>
      <group position={[-0.961, 0.333, -29.809]} rotation={[Math.PI, 0, Math.PI]} scale={0.612}>
        <mesh geometry={nodes.Sankofa_Stool010.geometry} material={newMaterials['weaving_Baked.001']} />
        <mesh geometry={nodes.Sankofa_Stool010_1.geometry} material={newMaterials['rattan_Baked.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/lighthomeoffice.glb')
