/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light2ndoffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Light2ndoffice.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[1.123, 0.607, -30.749]}>
        <mesh geometry={nodes.Vert002.geometry} material={newMaterials.wicker_basket_01_Baked} />
        <mesh geometry={nodes.Vert002_1.geometry} material={newMaterials.Minimalist_Coffee_Table_Baked} />
        <mesh geometry={nodes.Vert002_2.geometry} material={newMaterials.Magazine2_Baked} />
        <mesh geometry={nodes.Vert002_3.geometry} material={newMaterials.Magazines_Baked} />
        <mesh geometry={nodes.Vert002_4.geometry} material={newMaterials.PampassGrass_Baked} />
        <mesh geometry={nodes.Vert002_5.geometry} material={newMaterials['Ceramic and golden vase_Baked']} />
        <mesh geometry={nodes.Vert002_6.geometry} material={newMaterials['Ceramic Pampass_Baked']} />
        <mesh geometry={nodes.Vert002_7.geometry} material={newMaterials.Hopi_Baked} />
      </group>
      <mesh geometry={nodes.Folded_garment_stack_Baked.geometry} material={newMaterials['Folded garment stack_Baked']} position={[0.913, 0.25, -30.697]} />
      <mesh geometry={nodes.PlasticBox_Baked.geometry} material={newMaterials.PlasticBox_Baked} position={[1.442, 0.255, -30.715]} />
      <mesh geometry={nodes.Kilim_carpet_Baked.geometry} material={newMaterials['Kilim carpet_Baked']} position={[1.169, 0.138, -30.843]} />
      <group position={[2.437, 0.495, -31.813]}>
        <mesh geometry={nodes.Mesh006.geometry} material={newMaterials.PlantCouch_Baked} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={newMaterials.SmallCouchPlant_Baked} />
      </group>
      <mesh geometry={nodes.Big_Monstera_plant_Baked.geometry} material={newMaterials['Big Monstera plant_Baked']} position={[2.41, 0.604, -32.22]} />
      <mesh geometry={nodes.WhiteSofa_Baked.geometry} material={newMaterials.WhiteSofa_Baked} position={[1.211, 0.551, -32.206]} />
      <group position={[1.193, 0.554, -31.955]}>
        <mesh geometry={nodes.blanket_02_blanket_0001.geometry} material={newMaterials.ArmRestBlanket_Baked} />
        <mesh geometry={nodes.blanket_02_blanket_0001_1.geometry} material={newMaterials.FoldBlanket_Baked} />
      </group>
      <mesh geometry={nodes.PillowSofa1_Baked.geometry} material={newMaterials.PillowSofa1_Baked} position={[0.632, 0.682, -32.102]} />
      <mesh geometry={nodes.Pattern_cushion_Baked.geometry} material={newMaterials['Pattern cushion-D_Baked']} position={[1.42, 0.677, -32.196]} />
      <mesh geometry={nodes.PillowSofa2_Baked.geometry} material={newMaterials.PillowSofa2_Baked} position={[1.788, 0.669, -32.099]} />
      <mesh geometry={nodes.LovePillow003_Baked.geometry} material={newMaterials['LovePillow.003_Baked']} position={[0.717, 0.605, -31.941]} />
      <group position={[1.079, 0.595, -31.993]}>
        <mesh geometry={nodes.Plane021.geometry} material={newMaterials['Round Pillow_Baked']} />
        <mesh geometry={nodes.Plane021_1.geometry} material={newMaterials['Linen rustic pillow-02_Baked']} />
        <mesh geometry={nodes.Plane021_2.geometry} material={newMaterials.sweater_FIX_Baked} />
      </group>
      <group position={[1.028, 0.68, -32.17]}>
        <mesh geometry={nodes['302161597_002001'].geometry} material={newMaterials.Almofada_baked} />
        <mesh geometry={nodes['302161597_002001_1'].geometry} material={newMaterials['Almofada estampa B']} />
        <mesh geometry={nodes['302161597_002001_2'].geometry} material={newMaterials['Linha preta']} />
      </group>
      <group position={[1.211, 1.231, -32.51]}>
        <mesh geometry={nodes.Object_0020.geometry} material={newMaterials.WindowPlant_Baked} />
        <mesh geometry={nodes.Object_0020_1.geometry} material={newMaterials['Succulent plant_Baked']} />
        <mesh geometry={nodes.Object_0020_2.geometry} material={newMaterials.WindowBush1_Baked} />
        <mesh geometry={nodes.Object_0020_3.geometry} material={newMaterials['Long curtain_Baked']} />
      </group>
      <mesh geometry={nodes.WindowBush2_Baked.geometry} material={newMaterials.WindowBush2_Baked} position={[0.851, 0.866, -32.594]} />
    </group>
  )
}

useGLTF.preload('/Light2ndoffice.glb')
